<template><div><h1 id="cocos-creator问题集" tabindex="-1"><a class="header-anchor" href="#cocos-creator问题集"><span>Cocos Creator问题集</span></a></h1>
<h2 id="小程序真机无法显示ttf字体" tabindex="-1"><a class="header-anchor" href="#小程序真机无法显示ttf字体"><span>小程序真机无法显示ttf字体</span></a></h2>
<p>根据论坛里面说的是，主要的原因是因为字体的<code v-pre>font-family</code>名字里面带有空格。</p>
<p>需要使用字体修改工具<a href="https://www.high-logic.com/font-editor/fontcreator" target="_blank" rel="noopener noreferrer">High-Logic FontCreator</a>来修改<code v-pre>font-family</code>名，修改之后，确实生效了。</p>
<ol>
<li>打开<code v-pre>FontCreator</code>，将<code v-pre>ttf文件</code>拖到FontCreator打开。</li>
<li>菜单项选择：<code v-pre>Font</code> -&gt; <code v-pre>Properties</code>，打开<code v-pre>Font Properties</code>弹窗。</li>
<li>在弹窗里面看到有几个子标签页，其中Identification标签页里面的 Font Family即为字体的英文名，自行修改成自己需要的值。</li>
<li>在Custom标签页里面，可以看到列表里面的第一列是语言ID，第二列是Name ID，简体中文系统上，找到行 <code v-pre>Chinese-People's Republic of China  Font Family</code>，</li>
<li>繁体中文或者其他语言的系统下，应该是修改对应的行，没有的也可以Add添加新的行，这个我没有测试，猜测是这样。</li>
<li>修改完毕后点击OK保存。</li>
<li>菜单项选择：<code v-pre>File</code> -&gt; <code v-pre>Export Font As...</code> -&gt; <code v-pre>Export as Desktop Font(ttf/otf)</code>，弹出<code v-pre>Export as Desktop Font(ttf/otf)</code>窗口。</li>
<li>在弹出窗口中将Outline Format项，通过下拉选择TrueType，不建议选CFF（测试时这个选项可能Identification标签页里面字体名不生效）。</li>
<li>底部三个按钮点击<code v-pre>Export</code>即可。最终保存文件窗口自己选择文件格式。</li>
</ol>
<h2 id="failed-to-new-role-under-the-hood-typeerror-cannot-read-property-ins-of-undefined" tabindex="-1"><a class="header-anchor" href="#failed-to-new-role-under-the-hood-typeerror-cannot-read-property-ins-of-undefined"><span>Failed to <code v-pre>new Role()</code> under the hood, TypeError: Cannot read property 'ins' of undefined</span></a></h2>
<p>这是循环引用导致的问题。</p>
<p>当前类里面引用了另外一个ts文件里面的一个enum类型定义，另外一个ts文件里面的类又引用了当前类。</p>
<p>这个事儿，还挺好办的，只要把依赖的那个enum单独提取出来一个ts文件，然后import就可以了，问题解决。</p>
<h2 id="please-specifiy-a-default-value-for-animalitem-ani-park-exp-at-its-declaration" tabindex="-1"><a class="header-anchor" href="#please-specifiy-a-default-value-for-animalitem-ani-park-exp-at-its-declaration"><span>Please specifiy a default value for “AnimalItem.ani_park_exp” at its declaration:</span></a></h2>
<p>如果如下代码，就会报警告信息：</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token decorator"><span class="token at operator">@</span><span class="token function">property</span></span><span class="token punctuation">(</span>cc<span class="token punctuation">.</span>Node<span class="token punctuation">)</span></span>
<span class="line">Min<span class="token operator">:</span> cc<span class="token punctuation">.</span>Node<span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>只需要给一个初始值就可以了：</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token decorator"><span class="token at operator">@</span><span class="token function">property</span></span><span class="token punctuation">(</span>cc<span class="token punctuation">.</span>Node<span class="token punctuation">)</span></span>
<span class="line">Min<span class="token operator">:</span> cc<span class="token punctuation">.</span>Node <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">## 参考资料</span>
<span class="line"></span>
<span class="line"><span class="token operator">-</span> <span class="token punctuation">[</span>CocosCreator微信小游戏真机ttf字体不能正常显示<span class="token punctuation">]</span><span class="token punctuation">(</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span>blog<span class="token punctuation">.</span>asroads<span class="token punctuation">.</span>com<span class="token operator">/</span>post<span class="token operator">/</span>339e6f6c<span class="token punctuation">.</span>html<span class="token punctuation">)</span></span>
<span class="line"><span class="token operator">-</span> <span class="token punctuation">[</span>微信小游戏真机 <span class="token constant">TTF</span> 字体无效<span class="token punctuation">]</span><span class="token punctuation">(</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span>forum<span class="token punctuation">.</span>cocos<span class="token punctuation">.</span>org<span class="token operator">/</span>t<span class="token operator">/</span>topic<span class="token operator">/</span><span class="token number">145453</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token operator">-</span> <span class="token punctuation">[</span>微信小游戏 ttf字体 无效<span class="token punctuation">]</span><span class="token punctuation">(</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span>forum<span class="token punctuation">.</span>cocos<span class="token punctuation">.</span>org<span class="token operator">/</span>t<span class="token operator">/</span>topic<span class="token operator">/</span><span class="token number">148371</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token operator">-</span> <span class="token punctuation">[</span>修改<span class="token constant">TTF</span>文件或者otf文件或者woff文件内的字体名称<span class="token punctuation">]</span><span class="token punctuation">(</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span>cloud<span class="token punctuation">.</span>tencent<span class="token punctuation">.</span>com<span class="token operator">/</span>developer<span class="token operator">/</span>article<span class="token operator">/</span><span class="token number">1758463</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token operator">-</span> <span class="token punctuation">[</span>Cocos Creator 小游戏首屏加速显示<span class="token punctuation">]</span><span class="token punctuation">(</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span>blog<span class="token punctuation">.</span>asroads<span class="token punctuation">.</span>com<span class="token operator">/</span>post<span class="token operator">/</span>c50519e6<span class="token punctuation">.</span>html<span class="token punctuation">)</span></span>
<span class="line"><span class="token operator">-</span> <span class="token punctuation">[</span>微信小游戏的启动性能优化之首屏渲染<span class="token punctuation">]</span><span class="token punctuation">(</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span>developers<span class="token punctuation">.</span>weixin<span class="token punctuation">.</span>qq<span class="token punctuation">.</span>com<span class="token operator">/</span>community<span class="token operator">/</span>minigame<span class="token operator">/</span>article<span class="token operator">/</span>doc<span class="token operator">/</span>000c86f5ee81b8c05b2bc9cc650013<span class="token punctuation">)</span></span>
<span class="line"><span class="token operator">-</span> <span class="token punctuation">[</span>cocos creator <span class="token number">3.6</span><span class="token punctuation">.</span>x 版本<span class="token constant">H5</span>下 启动页做进度条加载<span class="token punctuation">]</span><span class="token punctuation">(</span>https<span class="token operator">:</span><span class="token operator">/</span><span class="token operator">/</span>juejin<span class="token punctuation">.</span>cn<span class="token operator">/</span>post<span class="token operator">/</span><span class="token number">7219272135817723965</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


