<template><div><h1 id="flutter使用sealed-class让状态类更强大" tabindex="-1"><a class="header-anchor" href="#flutter使用sealed-class让状态类更强大"><span>Flutter使用Sealed Class让状态类更强大</span></a></h1>
<p>记得之前在写Kotlin的时候，对于Kotlin所提供的<code v-pre>Sealed Class</code>的功能感到惊喜，我还给Sealed Class封上了enum 2.0的称号，它拥有Class的特性，可以将状态封装起来，使用<code v-pre>when</code>语法的时候，还可以详尽列出所有的子项，而在Flutter当中，其实也有<code v-pre>sealed class</code>可以用，在Dart 3.0中，也已经将sealed class加入到了Dart的武器库。</p>
<h2 id="enum" tabindex="-1"><a class="header-anchor" href="#enum"><span>enum</span></a></h2>
<p>假如，我们现在要实现一个 收音机 功能，我们可以使用enum声明其状态，代码如下：</p>
<div class="language-dart line-numbers-mode" data-highlighter="prismjs" data-ext="dart"><pre v-pre><code><span class="line"><span class="token keyword">enum</span> <span class="token class-name">Status</span> <span class="token punctuation">{</span>  </span>
<span class="line">  init<span class="token punctuation">,</span> playing<span class="token punctuation">,</span> paused<span class="token punctuation">,</span> stopped  </span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>如果我们要打印出现在的状态，我们可能会这样写：利用一个方法，传入enum，在这个方法里面判断该显示什么文字：</p>
<div class="language-dart line-numbers-mode" data-highlighter="prismjs" data-ext="dart"><pre v-pre><code><span class="line"><span class="token keyword">void</span> <span class="token function">displayStatus</span><span class="token punctuation">(</span><span class="token class-name">Status</span> status<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token keyword">switch</span> <span class="token punctuation">(</span>status<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">case</span> <span class="token class-name">Status</span><span class="token punctuation">.</span>init<span class="token punctuation">:</span></span>
<span class="line">      <span class="token function">print</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">'The radio is initializing'</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">      <span class="token keyword">break</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">case</span> <span class="token class-name">Status</span><span class="token punctuation">.</span>playing<span class="token punctuation">:</span></span>
<span class="line">      <span class="token function">print</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">'The radio is playing'</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">      <span class="token keyword">break</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">case</span> <span class="token class-name">Status</span><span class="token punctuation">.</span>paused<span class="token punctuation">:</span></span>
<span class="line">      <span class="token function">print</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">'The radio is paused'</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>  </span>
<span class="line">      <span class="token keyword">break</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">case</span> <span class="token class-name">Status</span><span class="token punctuation">.</span>stopped<span class="token punctuation">:</span></span>
<span class="line">      <span class="token function">print</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">'The radio is stopped'</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">      <span class="token keyword">break</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>但是，使用enum + function的方法会让我们定义的内容散布到各处，换而言之，我们使用这种方式时，打印方法的实现是在一个函数里面，而非在enum内，如此就很容易造成bug。</p>
<h2 id="sealed-class" tabindex="-1"><a class="header-anchor" href="#sealed-class"><span>Sealed class</span></a></h2>
<p>在这，我们可以使用 <code v-pre>sealed class</code> 来改写，如下：在class关键字前面加上<code v-pre>sealed</code>关键字之后，该类就成为了 <strong>sealed class(密封类型)</strong>。</p>
<p>接口定义：</p>
<div class="language-dart line-numbers-mode" data-highlighter="prismjs" data-ext="dart"><pre v-pre><code><span class="line">sealed <span class="token keyword">class</span> <span class="token class-name">SealedStatus</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token keyword">void</span> <span class="token function">display</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>继承实现类：</p>
<div class="language-dart line-numbers-mode" data-highlighter="prismjs" data-ext="dart"><pre v-pre><code><span class="line"><span class="token keyword">class</span> <span class="token class-name">Init</span> <span class="token keyword">extends</span> <span class="token class-name">SealedStatus</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token metadata function">@override</span></span>
<span class="line">  <span class="token keyword">void</span> <span class="token function">display</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token function">print</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">'The radio is initializing'</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"><span class="token keyword">class</span> <span class="token class-name">Playing</span> <span class="token keyword">extends</span> <span class="token class-name">SealedStatus</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token metadata function">@override</span></span>
<span class="line">  <span class="token keyword">void</span> <span class="token function">display</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token function">print</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">'The radio is playing'</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"><span class="token keyword">class</span> <span class="token class-name">Paused</span> <span class="token keyword">extends</span> <span class="token class-name">SealedStatus</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token metadata function">@override</span></span>
<span class="line">  <span class="token keyword">void</span> <span class="token function">display</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token function">print</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">'The radio is paused'</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"><span class="token keyword">class</span> <span class="token class-name">Stopped</span> <span class="token keyword">extends</span> <span class="token class-name">SealedStatus</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token metadata function">@override</span></span>
<span class="line">  <span class="token keyword">void</span> <span class="token function">display</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token function">print</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">'The radio is stopped'</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>接口调用：</p>
<div class="language-dart line-numbers-mode" data-highlighter="prismjs" data-ext="dart"><pre v-pre><code><span class="line"><span class="token function">displaySealedStatus</span><span class="token punctuation">(</span><span class="token class-name">SealedStatus</span> status<span class="token punctuation">)</span> <span class="token operator">=</span><span class="token operator">></span> status<span class="token punctuation">.</span><span class="token function">display</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="如此一来-我们就可以将函数变得更加的精简" tabindex="-1"><a class="header-anchor" href="#如此一来-我们就可以将函数变得更加的精简"><span>如此一来，我们就可以将函数变得更加的精简</span></a></h2>
<p>别忘记了 sealed class 支持 switch 列举：</p>
<p>定义接口</p>
<div class="language-dart line-numbers-mode" data-highlighter="prismjs" data-ext="dart"><pre v-pre><code><span class="line">sealed <span class="token keyword">class</span> <span class="token class-name">SealedStatus</span> <span class="token punctuation">{</span><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>继承类</p>
<div class="language-dart line-numbers-mode" data-highlighter="prismjs" data-ext="dart"><pre v-pre><code><span class="line"><span class="token keyword">class</span> <span class="token class-name">Init</span> <span class="token keyword">extends</span> <span class="token class-name">SealedStatus</span> <span class="token punctuation">{</span><span class="token punctuation">}</span></span>
<span class="line"><span class="token keyword">class</span> <span class="token class-name">Playing</span> <span class="token keyword">extends</span> <span class="token class-name">SealedStatus</span> <span class="token punctuation">{</span><span class="token punctuation">}</span> </span>
<span class="line"><span class="token keyword">class</span> <span class="token class-name">Paused</span> <span class="token keyword">extends</span> <span class="token class-name">SealedStatus</span> <span class="token punctuation">{</span><span class="token punctuation">}</span> </span>
<span class="line"><span class="token keyword">class</span> <span class="token class-name">Stopped</span> <span class="token keyword">extends</span> <span class="token class-name">SealedStatus</span> <span class="token punctuation">{</span><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>实现<code v-pre>displaySealedStatus2</code>方法：</p>
<div class="language-dart line-numbers-mode" data-highlighter="prismjs" data-ext="dart"><pre v-pre><code><span class="line"><span class="token function">displaySealedStatus2</span><span class="token punctuation">(</span><span class="token class-name">SealedStatus</span> status<span class="token punctuation">)</span> <span class="token operator">=</span><span class="token operator">></span> <span class="token keyword">switch</span> <span class="token punctuation">(</span>status<span class="token punctuation">)</span> <span class="token punctuation">{</span>  </span>
<span class="line">      <span class="token class-name">Init</span> _ <span class="token operator">=</span><span class="token operator">></span> <span class="token function">print</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">'The radio is initializing'</span></span><span class="token punctuation">)</span><span class="token punctuation">,</span>  </span>
<span class="line">      <span class="token class-name">Playing</span> _ <span class="token operator">=</span><span class="token operator">></span> <span class="token function">print</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">'The radio is playing'</span></span><span class="token punctuation">)</span><span class="token punctuation">,</span>  </span>
<span class="line">      <span class="token class-name">Paused</span> _ <span class="token operator">=</span><span class="token operator">></span> <span class="token function">print</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">'The radio is paused'</span></span><span class="token punctuation">)</span><span class="token punctuation">,</span>  </span>
<span class="line">      <span class="token class-name">Stopped</span> _ <span class="token operator">=</span><span class="token operator">></span> <span class="token function">print</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">'The radio is stopped'</span></span><span class="token punctuation">)</span>  </span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>displaySealedStatus2()</code>就像是Kotlin的 lambda表达式，可以直接回传一个方法。因为 sealed class 的特性，在 compile-time 的时候，就可以知道所有的子类，所以，函数的使用是安全的。</p>
<p>使用 sealed class 能够让编译期在 compile-time 的时候就知道有哪些子类型，所以也就能够在开发时找出 switch当中所遗漏的状态。</p>
<h2 id="sealed-class-bloc" tabindex="-1"><a class="header-anchor" href="#sealed-class-bloc"><span>Sealed class + BLoC</span></a></h2>
<p>BLoC 是 Flutter 中一个状态管理的工具，使用BLoC时，需要定义状态(state)、事件(event)，若是 Cubit（类似于BLoC，但是更为精简），虽然不需要定义事件（因为使用直接调用函数取代了事件传递），可还是需要定义状态的。</p>
<p>通常，在定义BLoC、Cubit的状态时，会将基本状态使用<code v-pre>abstract class</code>来声明，之后所有的状态都将会继承该基本状态类型。</p>
<p>如同上面的示例，我们来将 收音机 的状态改成可以在 BLoC 中使用的状态。</p>
<p>声明接口：</p>
<div class="language-dart line-numbers-mode" data-highlighter="prismjs" data-ext="dart"><pre v-pre><code><span class="line"><span class="token keyword">abstract</span> <span class="token keyword">class</span> <span class="token class-name">RadioState</span> <span class="token keyword">extends</span> <span class="token class-name">Equatable</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token keyword">const</span> <span class="token class-name">RadioState</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>继承实现：</p>
<div class="language-dart line-numbers-mode" data-highlighter="prismjs" data-ext="dart"><pre v-pre><code><span class="line"><span class="token keyword">class</span> <span class="token class-name">RadioInitial</span> <span class="token keyword">extends</span> <span class="token class-name">RadioState</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token metadata function">@override</span></span>
<span class="line">  <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Object</span><span class="token punctuation">></span></span> <span class="token keyword">get</span> props <span class="token operator">=</span><span class="token operator">></span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"><span class="token keyword">class</span> <span class="token class-name">RadioPlaying</span> <span class="token keyword">extends</span> <span class="token class-name">RadioState</span> <span class="token punctuation">{</span>  </span>
<span class="line">  <span class="token metadata function">@override</span></span>
<span class="line">  <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Object</span><span class="token punctuation">></span></span> <span class="token keyword">get</span> props <span class="token operator">=</span><span class="token operator">></span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"><span class="token keyword">class</span> <span class="token class-name">RadioPaused</span> <span class="token keyword">extends</span> <span class="token class-name">RadioState</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token metadata function">@override</span></span>
<span class="line">  <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Object</span><span class="token punctuation">></span></span> <span class="token keyword">get</span> props <span class="token operator">=</span><span class="token operator">></span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"><span class="token keyword">class</span> <span class="token class-name">RadioStopped</span> <span class="token keyword">extends</span> <span class="token class-name">RadioState</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token metadata function">@override</span></span>
<span class="line">  <span class="token class-name">List</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Object</span><span class="token punctuation">></span></span> <span class="token keyword">get</span> props <span class="token operator">=</span><span class="token operator">></span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在 Widget 内使用 BLoC 事，可以使用 BlocBuilder 来根据不同的状态来产生不同的 Widget， 如下：</p>
<div class="language-dart line-numbers-mode" data-highlighter="prismjs" data-ext="dart"><pre v-pre><code><span class="line"><span class="token class-name">BlocBuilder</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">RadioBloc</span><span class="token punctuation">,</span> <span class="token class-name">RadioState</span><span class="token punctuation">></span></span><span class="token punctuation">(</span>  </span>
<span class="line">  builder<span class="token punctuation">:</span> <span class="token punctuation">(</span><span class="token class-name">BuildContext</span> context<span class="token punctuation">,</span> state<span class="token punctuation">)</span> <span class="token punctuation">{</span>  </span>
<span class="line">    <span class="token keyword">if</span> <span class="token punctuation">(</span>state <span class="token operator">is</span> <span class="token class-name">RadioInitial</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>  </span>
<span class="line">      <span class="token keyword">return</span> <span class="token keyword">const</span> <span class="token class-name">Text</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">"Initial"</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>  </span>
<span class="line">    <span class="token punctuation">}</span>  </span>
<span class="line">    <span class="token keyword">if</span> <span class="token punctuation">(</span>state <span class="token operator">is</span> <span class="token class-name">RadioPlaying</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>  </span>
<span class="line">      <span class="token keyword">return</span> <span class="token keyword">const</span> <span class="token class-name">Text</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">"Loading"</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>  </span>
<span class="line">    <span class="token punctuation">}</span>  </span>
<span class="line">    <span class="token keyword">if</span> <span class="token punctuation">(</span>state <span class="token operator">is</span> <span class="token class-name">RadioPaused</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>  </span>
<span class="line">      <span class="token keyword">return</span> <span class="token keyword">const</span> <span class="token class-name">Text</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">"Paused"</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>  </span>
<span class="line">    <span class="token punctuation">}</span>  </span>
<span class="line">    <span class="token keyword">if</span> <span class="token punctuation">(</span>state <span class="token operator">is</span> <span class="token class-name">RadioStopped</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>  </span>
<span class="line">      <span class="token keyword">return</span> <span class="token keyword">const</span> <span class="token class-name">Text</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">"Stopped"</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>  </span>
<span class="line">    <span class="token punctuation">}</span>  </span>
<span class="line">    <span class="token keyword">return</span> <span class="token keyword">const</span> <span class="token class-name">CircularProgressIndicator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>  </span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span>  </span>
<span class="line"><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>使用 if 判断 state 是否为特定状态，再依不同状态产生不同的 Widget，这种很常见判断 BLoC 状态的方法，在这里我们可以改用 <code v-pre>switch</code> 来进行改写：</p>
<div class="language-dart line-numbers-mode" data-highlighter="prismjs" data-ext="dart"><pre v-pre><code><span class="line"><span class="token class-name">BlocBuilder</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">RadioBloc</span><span class="token punctuation">,</span> <span class="token class-name">RadioState</span><span class="token punctuation">></span></span><span class="token punctuation">(</span></span>
<span class="line">  builder<span class="token punctuation">:</span> <span class="token punctuation">(</span><span class="token class-name">BuildContext</span> context<span class="token punctuation">,</span> state<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">switch</span> <span class="token punctuation">(</span>state<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">      <span class="token keyword">case</span> <span class="token class-name">RadioInitial</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span></span>
<span class="line">        <span class="token keyword">return</span> <span class="token keyword">const</span> <span class="token class-name">Text</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">"Initial"</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">      <span class="token keyword">case</span> <span class="token class-name">RadioPlaying</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span></span>
<span class="line">        <span class="token keyword">return</span> <span class="token keyword">const</span> <span class="token class-name">Text</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">"Playing"</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">      <span class="token keyword">case</span> <span class="token class-name">RadioPaused</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span></span>
<span class="line">        <span class="token keyword">return</span> <span class="token keyword">const</span> <span class="token class-name">Text</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">"Paused"</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">      <span class="token keyword">case</span> <span class="token class-name">RadioStopped</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span></span>
<span class="line">        <span class="token keyword">return</span> <span class="token keyword">const</span> <span class="token class-name">Text</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">"Stopped"</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token keyword">const</span> <span class="token class-name">CircularProgressIndicator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>前面有提到，一般的Class是不支持switch列出所有可能的Class（因为编译器在compile-time还无法知道有哪些子类），假如我们犯了一个错，稍加了一个状态，那么，编译不会报错，而我们可能要到程序执行的时候才发现问题（甚至压根就没发现）。</p>
<div class="language-dart line-numbers-mode" data-highlighter="prismjs" data-ext="dart"><pre v-pre><code><span class="line"><span class="token class-name">BlocBuilder</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">RadioBloc</span><span class="token punctuation">,</span> <span class="token class-name">RadioState</span><span class="token punctuation">></span></span><span class="token punctuation">(</span></span>
<span class="line">  builder<span class="token punctuation">:</span> <span class="token punctuation">(</span><span class="token class-name">BuildContext</span> context<span class="token punctuation">,</span> state<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">switch</span> <span class="token punctuation">(</span>state<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">      <span class="token keyword">case</span> <span class="token class-name">RadioInitial</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span></span>
<span class="line">        <span class="token keyword">return</span> <span class="token keyword">const</span> <span class="token class-name">Text</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">"Initial"</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">      <span class="token keyword">case</span> <span class="token class-name">RadioPlaying</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span></span>
<span class="line">        <span class="token keyword">return</span> <span class="token keyword">const</span> <span class="token class-name">Text</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">"Playing"</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">     <span class="token comment">// case RadioPaused():   //&lt;- 少了 Paused 还是可以正常编译，不会发生错误</span></span>
<span class="line">     <span class="token comment">//   return const Text("Paused");</span></span>
<span class="line">      <span class="token keyword">case</span> <span class="token class-name">RadioStopped</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span></span>
<span class="line">        <span class="token keyword">return</span> <span class="token keyword">const</span> <span class="token class-name">Text</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">"Stopped"</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token keyword">const</span> <span class="token class-name">CircularProgressIndicator</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>而如果我们将接口类型改为使用<code v-pre>sealed class</code>来声明，这个问题就能够在开发时就被发现。</p>
<p>将<code v-pre>abstract class RadioState{}</code>改为<code v-pre>sealed class RadioState {}</code>:</p>
<div class="language-dart line-numbers-mode" data-highlighter="prismjs" data-ext="dart"><pre v-pre><code><span class="line">sealed <span class="token keyword">class</span> <span class="token class-name">RadioState</span> <span class="token keyword">extends</span> <span class="token class-name">Equatable</span> <span class="token punctuation">{</span>  </span>
<span class="line">  <span class="token keyword">const</span> <span class="token class-name">RadioState</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>  </span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在IDE中，我们就会发现 switch 会出现 <code v-pre>compile-time error</code>：</p>
<p><img src="/assets/images/flutter/sealed_class_not_enough_state.png" alt=""></p>
<p>这时候，我们就必须要在 switch 中填入所有的状态，这样才可以IDE不报 compile-time error，并能够执行编译。</p>
<p><img src="/assets/images/flutter/sealed_class_enough_state.png" alt=""></p>
<p>Bloc插件 4.0.0 版本中已经自动将基本状态的Class改为了sealed class。</p>
<p><img src="/assets/images/flutter/bloc_plugin.png" alt=""></p>
<h2 id="结论" tabindex="-1"><a class="header-anchor" href="#结论"><span>结论</span></a></h2>
<p>Sealed class 是一个很好用的工具，将Class使用 sealed class 进行声明，就可以让我们在开发的时候避免踩到难以发现的雷。如同上面的示例，使用BLoC的时候，若在BlocBuilder里面有状态忘记加了，就有可能造成误操作，而使用 sealed class 就可以避免我们的粗心大意所导致的难发现的错误，让我们可以及早的发现和排雷。</p>
<h2 id="翻译自" tabindex="-1"><a class="header-anchor" href="#翻译自"><span>翻译自</span></a></h2>
<p><a href="https://andyludeveloper.medium.com/flutter-%E4%BD%BF%E7%94%A8-sealed-class-%E8%AE%93%E4%BD%A0%E7%9A%84%E9%A1%9E%E5%88%A5%E6%9B%B4%E5%BC%B7%E5%A4%A7-59152a47f666" target="_blank" rel="noopener noreferrer">Flutter — 使用 Sealed class 讓你的類別更強大</a></p>
</div></template>


