<template><div><h1 id="gowind-admin-风行-—-开箱即用的企业级全栈中后台框架-站内信" tabindex="-1"><a class="header-anchor" href="#gowind-admin-风行-—-开箱即用的企业级全栈中后台框架-站内信"><span>GoWind Admin｜风行 — 开箱即用的企业级全栈中后台框架：站内信</span></a></h1>
<p>在企业级后台管理系统中，站内信是核心沟通组件之一，承担着系统通知、用户互动、业务提醒等关键场景需求。基于 Go 语言微服务框架 <a href="https://github.com/go-kratos/kratos" target="_blank" rel="noopener noreferrer">Kratos</a> 构建的 <a href="https://github.com/tx7do/go-wind-admin" target="_blank" rel="noopener noreferrer">Go Wind Admin</a>，将站内信模块封装为「开箱即用」的标准化组件，无需从零开发即可快速集成，大幅降低开发成本。</p>
<p>本文将从功能价值、技术设计、实操使用、扩展场景四个维度，全面解析 Go Wind Admin 站内信模块。​</p>
<h2 id="一、go-wind-admin-与站内信的核心价值​" tabindex="-1"><a class="header-anchor" href="#一、go-wind-admin-与站内信的核心价值​"><span>一、Go Wind Admin 与站内信的核心价值​</span></a></h2>
<h3 id="_1-1-go-wind-admin-定位​" tabindex="-1"><a class="header-anchor" href="#_1-1-go-wind-admin-定位​"><span>1.1 Go Wind Admin 定位​</span></a></h3>
<p>Go Wind Admin 是基于B站 Kratos 微服务框架开发的企业级后台管理系统解决方案，内置用户管理、权限控制、日志审计、配置中心等核心模块，支持 Go 生态主流技术栈（GORM、Redis、ProtoBuf 等），主打「低代码集成」与「高扩展性」，适用于中小团队快速搭建后台系统。​</p>
<h3 id="_1-2-站内信功能的核心场景​" tabindex="-1"><a class="header-anchor" href="#_1-2-站内信功能的核心场景​"><span>1.2 站内信功能的核心场景​</span></a></h3>
<p>站内信作为系统内「非实时但可靠」的沟通载体，核心解决以下问题：​</p>
<ul>
<li>系统通知：如账号状态变更（禁用 / 启用）、权限调整、订单审核结果等业务通知；​</li>
<li>用户互动：如管理员向指定用户发送定向提醒、用户间基于系统的留言沟通；​</li>
<li>消息追溯：所有消息持久化存储，支持历史查询，满足审计与问题排查需求；​</li>
<li>低干扰触达：区别于短信 / 邮件的外部推送，站内信仅在系统内展示，避免用户信息过载。</li>
</ul>
<h2 id="二、站内信核心技术设计​" tabindex="-1"><a class="header-anchor" href="#二、站内信核心技术设计​"><span>二、站内信核心技术设计​</span></a></h2>
<p>Go Wind Admin 站内信模块遵循「简洁可靠、易于扩展」的设计原则，核心分为数据模型与业务逻辑两层。​</p>
<h3 id="_2-1-数据模型设计-postgresql-​" tabindex="-1"><a class="header-anchor" href="#_2-1-数据模型设计-postgresql-​"><span>2.1 数据模型设计（Postgresql）​</span></a></h3>
<div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code><span class="line"><span class="token keyword">CREATE</span> <span class="token keyword">TABLE</span> <span class="token keyword">public</span><span class="token punctuation">.</span>internal_messages <span class="token punctuation">(</span></span>
<span class="line">    id          <span class="token keyword">bigint</span> generated <span class="token keyword">by</span> <span class="token keyword">default</span> <span class="token keyword">as</span> <span class="token keyword">identity</span> <span class="token keyword">primary</span> <span class="token keyword">key</span> <span class="token keyword">COMMENT</span> <span class="token string">'id'</span><span class="token punctuation">,</span></span>
<span class="line">    created_at  <span class="token keyword">timestamp</span> <span class="token keyword">with</span> <span class="token keyword">time</span> zone <span class="token keyword">COMMENT</span> <span class="token string">'创建时间'</span><span class="token punctuation">,</span></span>
<span class="line">    updated_at  <span class="token keyword">timestamp</span> <span class="token keyword">with</span> <span class="token keyword">time</span> zone <span class="token keyword">COMMENT</span> <span class="token string">'更新时间'</span><span class="token punctuation">,</span></span>
<span class="line">    deleted_at  <span class="token keyword">timestamp</span> <span class="token keyword">with</span> <span class="token keyword">time</span> zone <span class="token keyword">COMMENT</span> <span class="token string">'删除时间'</span><span class="token punctuation">,</span></span>
<span class="line">    created_by  <span class="token keyword">bigint</span> <span class="token keyword">COMMENT</span> <span class="token string">'创建者ID'</span><span class="token punctuation">,</span></span>
<span class="line">    updated_by  <span class="token keyword">bigint</span> <span class="token keyword">COMMENT</span> <span class="token string">'更新者ID'</span><span class="token punctuation">,</span></span>
<span class="line">    deleted_by  <span class="token keyword">bigint</span> <span class="token keyword">COMMENT</span> <span class="token string">'删除者ID'</span><span class="token punctuation">,</span></span>
<span class="line">    tenant_id   <span class="token keyword">bigint</span> <span class="token keyword">COMMENT</span> <span class="token string">'租户ID'</span><span class="token punctuation">,</span></span>
<span class="line">    title       <span class="token keyword">varchar</span> <span class="token keyword">COMMENT</span> <span class="token string">'消息标题'</span><span class="token punctuation">,</span></span>
<span class="line">    content     <span class="token keyword">varchar</span> <span class="token keyword">COMMENT</span> <span class="token string">'消息内容'</span><span class="token punctuation">,</span></span>
<span class="line">    sender_id   <span class="token keyword">bigint</span> <span class="token keyword">COMMENT</span> <span class="token string">'发送者用户ID'</span><span class="token punctuation">,</span></span>
<span class="line">    category_id <span class="token keyword">bigint</span> <span class="token keyword">COMMENT</span> <span class="token string">'分类ID'</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token keyword">status</span>      <span class="token keyword">varchar</span> <span class="token keyword">default</span> <span class="token string">'DRAFT'</span>::<span class="token keyword">character</span> <span class="token keyword">varying</span> <span class="token keyword">COMMENT</span> <span class="token string">'消息状态'</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token keyword">type</span>        <span class="token keyword">varchar</span> <span class="token keyword">default</span> <span class="token string">'NOTIFICATION'</span>::<span class="token keyword">character</span> <span class="token keyword">varying</span> <span class="token keyword">COMMENT</span> <span class="token string">'消息类型'</span></span>
<span class="line"><span class="token punctuation">)</span> <span class="token keyword">COMMENT</span> <span class="token string">'站内信消息表'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">CREATE</span> <span class="token keyword">TABLE</span> <span class="token keyword">public</span><span class="token punctuation">.</span>internal_message_recipients <span class="token punctuation">(</span></span>
<span class="line">    id                <span class="token keyword">bigint</span> generated <span class="token keyword">by</span> <span class="token keyword">default</span> <span class="token keyword">as</span> <span class="token keyword">identity</span> <span class="token keyword">primary</span> <span class="token keyword">key</span> <span class="token keyword">COMMENT</span> <span class="token string">'id'</span><span class="token punctuation">,</span></span>
<span class="line">    created_at        <span class="token keyword">timestamp</span> <span class="token keyword">with</span> <span class="token keyword">time</span> zone <span class="token keyword">COMMENT</span> <span class="token string">'创建时间'</span><span class="token punctuation">,</span></span>
<span class="line">    updated_at        <span class="token keyword">timestamp</span> <span class="token keyword">with</span> <span class="token keyword">time</span> zone <span class="token keyword">COMMENT</span> <span class="token string">'更新时间'</span><span class="token punctuation">,</span></span>
<span class="line">    deleted_at        <span class="token keyword">timestamp</span> <span class="token keyword">with</span> <span class="token keyword">time</span> zone <span class="token keyword">COMMENT</span> <span class="token string">'删除时间'</span><span class="token punctuation">,</span></span>
<span class="line">    tenant_id         <span class="token keyword">bigint</span> <span class="token keyword">COMMENT</span> <span class="token string">'租户ID'</span><span class="token punctuation">,</span></span>
<span class="line">    message_id        <span class="token keyword">bigint</span> <span class="token keyword">COMMENT</span> <span class="token string">'站内信内容ID'</span><span class="token punctuation">,</span></span>
<span class="line">    recipient_user_id <span class="token keyword">bigint</span> <span class="token keyword">COMMENT</span> <span class="token string">'接收者用户ID'</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token keyword">status</span>            <span class="token keyword">varchar</span> <span class="token keyword">COMMENT</span> <span class="token string">'消息状态'</span><span class="token punctuation">,</span></span>
<span class="line">    received_at       <span class="token keyword">timestamp</span> <span class="token keyword">with</span> <span class="token keyword">time</span> zone <span class="token keyword">COMMENT</span> <span class="token string">'消息到达用户收件箱的时间'</span><span class="token punctuation">,</span></span>
<span class="line">    read_at           <span class="token keyword">timestamp</span> <span class="token keyword">with</span> <span class="token keyword">time</span> zone <span class="token keyword">COMMENT</span> <span class="token string">'用户阅读消息的时间'</span></span>
<span class="line"><span class="token punctuation">)</span> <span class="token keyword">COMMENT</span> <span class="token string">'站内信消息用户接收信息表'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">CREATE</span> <span class="token keyword">TABLE</span> <span class="token keyword">public</span><span class="token punctuation">.</span>internal_message_categories <span class="token punctuation">(</span></span>
<span class="line">    id         <span class="token keyword">bigint</span> generated <span class="token keyword">by</span> <span class="token keyword">default</span> <span class="token keyword">as</span> <span class="token keyword">identity</span> <span class="token keyword">primary</span> <span class="token keyword">key</span> <span class="token keyword">COMMENT</span> <span class="token string">'id'</span><span class="token punctuation">,</span></span>
<span class="line">    created_at <span class="token keyword">timestamp</span> <span class="token keyword">with</span> <span class="token keyword">time</span> zone        <span class="token keyword">COMMENT</span> <span class="token string">'创建时间'</span><span class="token punctuation">,</span></span>
<span class="line">    updated_at <span class="token keyword">timestamp</span> <span class="token keyword">with</span> <span class="token keyword">time</span> zone        <span class="token keyword">COMMENT</span> <span class="token string">'更新时间'</span><span class="token punctuation">,</span></span>
<span class="line">    deleted_at <span class="token keyword">timestamp</span> <span class="token keyword">with</span> <span class="token keyword">time</span> zone        <span class="token keyword">COMMENT</span> <span class="token string">'删除时间'</span><span class="token punctuation">,</span></span>
<span class="line">    created_by <span class="token keyword">bigint</span>        <span class="token keyword">COMMENT</span> <span class="token string">'创建者ID'</span><span class="token punctuation">,</span></span>
<span class="line">    updated_by <span class="token keyword">bigint</span>        <span class="token keyword">COMMENT</span> <span class="token string">'更新者ID'</span><span class="token punctuation">,</span></span>
<span class="line">    deleted_by <span class="token keyword">bigint</span>        <span class="token keyword">COMMENT</span> <span class="token string">'删除者ID'</span><span class="token punctuation">,</span></span>
<span class="line">    is_enabled <span class="token keyword">boolean</span> <span class="token keyword">default</span> <span class="token boolean">true</span>        <span class="token keyword">COMMENT</span> <span class="token string">'是否启用'</span><span class="token punctuation">,</span></span>
<span class="line">    sort_order <span class="token keyword">integer</span> <span class="token keyword">default</span> <span class="token number">0</span>        <span class="token keyword">COMMENT</span> <span class="token string">'排序顺序，值越小越靠前'</span><span class="token punctuation">,</span></span>
<span class="line">    remark     <span class="token keyword">varchar</span>        <span class="token keyword">COMMENT</span> <span class="token string">'备注'</span><span class="token punctuation">,</span></span>
<span class="line">    tenant_id  <span class="token keyword">bigint</span>        <span class="token keyword">COMMENT</span> <span class="token string">'租户ID'</span><span class="token punctuation">,</span></span>
<span class="line">    name       <span class="token keyword">varchar</span>        <span class="token keyword">COMMENT</span> <span class="token string">'名称'</span><span class="token punctuation">,</span></span>
<span class="line">    code       <span class="token keyword">varchar</span>        <span class="token keyword">COMMENT</span> <span class="token string">'编码'</span><span class="token punctuation">,</span></span>
<span class="line">    icon_url   <span class="token keyword">varchar</span>        <span class="token keyword">COMMENT</span> <span class="token string">'图标URL'</span><span class="token punctuation">,</span></span>
<span class="line">    parent_id  <span class="token keyword">bigint</span></span>
<span class="line">        <span class="token keyword">constraint</span> internal_message_categories_in_8a268228b9922ecb0c6e7d2099d6aa98</span>
<span class="line">            <span class="token keyword">references</span> <span class="token keyword">public</span><span class="token punctuation">.</span>internal_message_categories</span>
<span class="line">            <span class="token keyword">on</span> <span class="token keyword">delete</span> <span class="token keyword">set</span> <span class="token boolean">null</span></span>
<span class="line">        <span class="token keyword">COMMENT</span> <span class="token string">'父节点ID'</span></span>
<span class="line"><span class="token punctuation">)</span> <span class="token keyword">COMMENT</span> <span class="token string">'站内信消息分类表'</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>目前，站内信功能只设计了三张表，用于系统通知。</p>
<p>在 Go Wind Admin 中，数据模型已通过 Ent的Schema 进行了定义，开发者可直接调用：​</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go"><pre v-pre><code><span class="line"><span class="token comment">// app/admin/service/internal/data/ent/schema/internal_message.go</span></span>
<span class="line"><span class="token keyword">package</span> schema</span>
<span class="line"></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">(</span></span>
<span class="line">	<span class="token string">"entgo.io/ent"</span></span>
<span class="line">	<span class="token string">"entgo.io/ent/dialect/entsql"</span></span>
<span class="line">	<span class="token string">"entgo.io/ent/schema"</span></span>
<span class="line">	<span class="token string">"entgo.io/ent/schema/field"</span></span>
<span class="line">	<span class="token string">"github.com/tx7do/go-utils/entgo/mixin"</span></span>
<span class="line"><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// InternalMessage holds the schema definition for the InternalMessage entity.</span></span>
<span class="line"><span class="token keyword">type</span> InternalMessage <span class="token keyword">struct</span> <span class="token punctuation">{</span></span>
<span class="line">	ent<span class="token punctuation">.</span>Schema</span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>InternalMessage<span class="token punctuation">)</span> <span class="token function">Annotations</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>schema<span class="token punctuation">.</span>Annotation <span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">return</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>schema<span class="token punctuation">.</span>Annotation<span class="token punctuation">{</span></span>
<span class="line">		entsql<span class="token punctuation">.</span>Annotation<span class="token punctuation">{</span></span>
<span class="line">			Table<span class="token punctuation">:</span>     <span class="token string">"internal_messages"</span><span class="token punctuation">,</span></span>
<span class="line">			Charset<span class="token punctuation">:</span>   <span class="token string">"utf8mb4"</span><span class="token punctuation">,</span></span>
<span class="line">			Collation<span class="token punctuation">:</span> <span class="token string">"utf8mb4_bin"</span><span class="token punctuation">,</span></span>
<span class="line">		<span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">		entsql<span class="token punctuation">.</span><span class="token function">WithComments</span><span class="token punctuation">(</span><span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">		schema<span class="token punctuation">.</span><span class="token function">Comment</span><span class="token punctuation">(</span><span class="token string">"站内信消息表"</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Fields of the InternalMessage.</span></span>
<span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>InternalMessage<span class="token punctuation">)</span> <span class="token function">Fields</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>ent<span class="token punctuation">.</span>Field <span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">return</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>ent<span class="token punctuation">.</span>Field<span class="token punctuation">{</span></span>
<span class="line">		field<span class="token punctuation">.</span><span class="token function">String</span><span class="token punctuation">(</span><span class="token string">"title"</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Comment</span><span class="token punctuation">(</span><span class="token string">"消息标题"</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Optional</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Nillable</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"></span>
<span class="line">		field<span class="token punctuation">.</span><span class="token function">String</span><span class="token punctuation">(</span><span class="token string">"content"</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Comment</span><span class="token punctuation">(</span><span class="token string">"消息内容"</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Optional</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Nillable</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"></span>
<span class="line">		field<span class="token punctuation">.</span><span class="token function">Uint32</span><span class="token punctuation">(</span><span class="token string">"sender_id"</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Comment</span><span class="token punctuation">(</span><span class="token string">"发送者用户ID"</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Optional</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Nillable</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"></span>
<span class="line">		field<span class="token punctuation">.</span><span class="token function">Uint32</span><span class="token punctuation">(</span><span class="token string">"category_id"</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Comment</span><span class="token punctuation">(</span><span class="token string">"分类ID"</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Optional</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Nillable</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"></span>
<span class="line">		field<span class="token punctuation">.</span><span class="token function">Enum</span><span class="token punctuation">(</span><span class="token string">"status"</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Comment</span><span class="token punctuation">(</span><span class="token string">"消息状态"</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">NamedValues</span><span class="token punctuation">(</span></span>
<span class="line">				<span class="token string">"Draft"</span><span class="token punctuation">,</span> <span class="token string">"DRAFT"</span><span class="token punctuation">,</span></span>
<span class="line">				<span class="token string">"Published"</span><span class="token punctuation">,</span> <span class="token string">"PUBLISHED"</span><span class="token punctuation">,</span></span>
<span class="line">				<span class="token string">"Scheduled"</span><span class="token punctuation">,</span> <span class="token string">"SCHEDULED"</span><span class="token punctuation">,</span></span>
<span class="line">				<span class="token string">"Revoked"</span><span class="token punctuation">,</span> <span class="token string">"REVOKED"</span><span class="token punctuation">,</span></span>
<span class="line">				<span class="token string">"Archived"</span><span class="token punctuation">,</span> <span class="token string">"ARCHIVED"</span><span class="token punctuation">,</span></span>
<span class="line">				<span class="token string">"Deleted"</span><span class="token punctuation">,</span> <span class="token string">"DELETED"</span><span class="token punctuation">,</span></span>
<span class="line">			<span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Default</span><span class="token punctuation">(</span><span class="token string">"DRAFT"</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Optional</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Nillable</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"></span>
<span class="line">		field<span class="token punctuation">.</span><span class="token function">Enum</span><span class="token punctuation">(</span><span class="token string">"type"</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Comment</span><span class="token punctuation">(</span><span class="token string">"消息类型"</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">NamedValues</span><span class="token punctuation">(</span></span>
<span class="line">				<span class="token string">"Notification"</span><span class="token punctuation">,</span> <span class="token string">"NOTIFICATION"</span><span class="token punctuation">,</span></span>
<span class="line">				<span class="token string">"Private"</span><span class="token punctuation">,</span> <span class="token string">"PRIVATE"</span><span class="token punctuation">,</span></span>
<span class="line">				<span class="token string">"Group"</span><span class="token punctuation">,</span> <span class="token string">"GROUP"</span><span class="token punctuation">,</span></span>
<span class="line">			<span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Default</span><span class="token punctuation">(</span><span class="token string">"NOTIFICATION"</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Optional</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span></span>
<span class="line">			<span class="token function">Nillable</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Mixin of the InternalMessage.</span></span>
<span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>InternalMessage<span class="token punctuation">)</span> <span class="token function">Mixin</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>ent<span class="token punctuation">.</span>Mixin <span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">return</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>ent<span class="token punctuation">.</span>Mixin<span class="token punctuation">{</span></span>
<span class="line">		mixin<span class="token punctuation">.</span>AutoIncrementId<span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">		mixin<span class="token punctuation">.</span>TimeAt<span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">		mixin<span class="token punctuation">.</span>OperatorID<span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">		mixin<span class="token punctuation">.</span>TenantID<span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-2-核心业务逻辑​" tabindex="-1"><a class="header-anchor" href="#_2-2-核心业务逻辑​"><span>2.2 核心业务逻辑​</span></a></h3>
<p>Go Wind Admin 已封装站内信全生命周期逻辑，核心流程如下：​</p>
<ol>
<li>参数校验</li>
<li>数据组装</li>
<li>将站内信消息存入数据库；</li>
<li>将站内信消息分发给用户的收件箱；</li>
<li>通过SSE通知前端。</li>
</ol>
<p>核心代码片段（发送逻辑）：​</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go"><pre v-pre><code><span class="line"><span class="token comment">// app/admin/service/internal/service/internal_message_service.go</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// SendMessage 发送消息</span></span>
<span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>s <span class="token operator">*</span>InternalMessageService<span class="token punctuation">)</span> <span class="token function">SendMessage</span><span class="token punctuation">(</span>ctx context<span class="token punctuation">.</span>Context<span class="token punctuation">,</span> req <span class="token operator">*</span>internalMessageV1<span class="token punctuation">.</span>SendMessageRequest<span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token operator">*</span>internalMessageV1<span class="token punctuation">.</span>SendMessageResponse<span class="token punctuation">,</span> <span class="token builtin">error</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">	<span class="token comment">// 获取操作人信息</span></span>
<span class="line">	operator<span class="token punctuation">,</span> err <span class="token operator">:=</span> auth<span class="token punctuation">.</span><span class="token function">FromContext</span><span class="token punctuation">(</span>ctx<span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">if</span> err <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span></span>
<span class="line">		<span class="token keyword">return</span> <span class="token boolean">nil</span><span class="token punctuation">,</span> err</span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">	now <span class="token operator">:=</span> time<span class="token punctuation">.</span><span class="token function">Now</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">var</span> msg <span class="token operator">*</span>internalMessageV1<span class="token punctuation">.</span>InternalMessage</span>
<span class="line">	<span class="token keyword">if</span> msg<span class="token punctuation">,</span> err <span class="token operator">=</span> s<span class="token punctuation">.</span>internalMessageRepo<span class="token punctuation">.</span><span class="token function">Create</span><span class="token punctuation">(</span>ctx<span class="token punctuation">,</span> <span class="token operator">&amp;</span>internalMessageV1<span class="token punctuation">.</span>CreateInternalMessageRequest<span class="token punctuation">{</span></span>
<span class="line">		Data<span class="token punctuation">:</span> <span class="token operator">&amp;</span>internalMessageV1<span class="token punctuation">.</span>InternalMessage<span class="token punctuation">{</span></span>
<span class="line">			Title<span class="token punctuation">:</span>      req<span class="token punctuation">.</span>Title<span class="token punctuation">,</span></span>
<span class="line">			Content<span class="token punctuation">:</span>    trans<span class="token punctuation">.</span><span class="token function">Ptr</span><span class="token punctuation">(</span>req<span class="token punctuation">.</span><span class="token function">GetContent</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">			Status<span class="token punctuation">:</span>     trans<span class="token punctuation">.</span><span class="token function">Ptr</span><span class="token punctuation">(</span>internalMessageV1<span class="token punctuation">.</span>InternalMessage_PUBLISHED<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">			Type<span class="token punctuation">:</span>       trans<span class="token punctuation">.</span><span class="token function">Ptr</span><span class="token punctuation">(</span>req<span class="token punctuation">.</span><span class="token function">GetType</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">			CategoryId<span class="token punctuation">:</span> req<span class="token punctuation">.</span>CategoryId<span class="token punctuation">,</span></span>
<span class="line">			CreatedBy<span class="token punctuation">:</span>  trans<span class="token punctuation">.</span><span class="token function">Ptr</span><span class="token punctuation">(</span>operator<span class="token punctuation">.</span><span class="token function">GetUserId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">			CreatedAt<span class="token punctuation">:</span>  timeutil<span class="token punctuation">.</span><span class="token function">TimeToTimestamppb</span><span class="token punctuation">(</span><span class="token operator">&amp;</span>now<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">		<span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">	<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span> err <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span></span>
<span class="line">		s<span class="token punctuation">.</span>log<span class="token punctuation">.</span><span class="token function">Errorf</span><span class="token punctuation">(</span><span class="token string">"create internal message failed: %s"</span><span class="token punctuation">,</span> err<span class="token punctuation">)</span></span>
<span class="line">		<span class="token keyword">return</span> <span class="token boolean">nil</span><span class="token punctuation">,</span> err</span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">if</span> req<span class="token punctuation">.</span><span class="token function">GetTargetAll</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">		users<span class="token punctuation">,</span> err <span class="token operator">:=</span> s<span class="token punctuation">.</span>userRepo<span class="token punctuation">.</span><span class="token function">List</span><span class="token punctuation">(</span>ctx<span class="token punctuation">,</span> <span class="token operator">&amp;</span>pagination<span class="token punctuation">.</span>PagingRequest<span class="token punctuation">{</span>NoPaging<span class="token punctuation">:</span> trans<span class="token punctuation">.</span><span class="token function">Ptr</span><span class="token punctuation">(</span><span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">		<span class="token keyword">if</span> err <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span></span>
<span class="line">			s<span class="token punctuation">.</span>log<span class="token punctuation">.</span><span class="token function">Errorf</span><span class="token punctuation">(</span><span class="token string">"send message failed, list users failed, %s"</span><span class="token punctuation">,</span> err<span class="token punctuation">)</span></span>
<span class="line">		<span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span></span>
<span class="line">			<span class="token keyword">for</span> <span class="token boolean">_</span><span class="token punctuation">,</span> user <span class="token operator">:=</span> <span class="token keyword">range</span> users<span class="token punctuation">.</span>Items <span class="token punctuation">{</span></span>
<span class="line">				<span class="token boolean">_</span> <span class="token operator">=</span> s<span class="token punctuation">.</span><span class="token function">sendNotification</span><span class="token punctuation">(</span>ctx<span class="token punctuation">,</span> msg<span class="token punctuation">.</span><span class="token function">GetId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> user<span class="token punctuation">.</span><span class="token function">GetId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> operator<span class="token punctuation">.</span><span class="token function">GetUserId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token operator">&amp;</span>now<span class="token punctuation">,</span> msg<span class="token punctuation">.</span><span class="token function">GetTitle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> msg<span class="token punctuation">.</span><span class="token function">GetContent</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">			<span class="token punctuation">}</span></span>
<span class="line">		<span class="token punctuation">}</span></span>
<span class="line">	<span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span></span>
<span class="line">		<span class="token keyword">if</span> req<span class="token punctuation">.</span>RecipientUserId <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span></span>
<span class="line">			<span class="token boolean">_</span> <span class="token operator">=</span> s<span class="token punctuation">.</span><span class="token function">sendNotification</span><span class="token punctuation">(</span>ctx<span class="token punctuation">,</span> msg<span class="token punctuation">.</span><span class="token function">GetId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> req<span class="token punctuation">.</span><span class="token function">GetRecipientUserId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> operator<span class="token punctuation">.</span><span class="token function">GetUserId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token operator">&amp;</span>now<span class="token punctuation">,</span> msg<span class="token punctuation">.</span><span class="token function">GetTitle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> msg<span class="token punctuation">.</span><span class="token function">GetContent</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">		<span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span></span>
<span class="line">			<span class="token keyword">if</span> <span class="token function">len</span><span class="token punctuation">(</span>req<span class="token punctuation">.</span>TargetUserIds<span class="token punctuation">)</span> <span class="token operator">!=</span> <span class="token number">0</span> <span class="token punctuation">{</span></span>
<span class="line">				<span class="token keyword">for</span> <span class="token boolean">_</span><span class="token punctuation">,</span> uid <span class="token operator">:=</span> <span class="token keyword">range</span> req<span class="token punctuation">.</span>TargetUserIds <span class="token punctuation">{</span></span>
<span class="line">					<span class="token boolean">_</span> <span class="token operator">=</span> s<span class="token punctuation">.</span><span class="token function">sendNotification</span><span class="token punctuation">(</span>ctx<span class="token punctuation">,</span> msg<span class="token punctuation">.</span><span class="token function">GetId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> uid<span class="token punctuation">,</span> operator<span class="token punctuation">.</span><span class="token function">GetUserId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token operator">&amp;</span>now<span class="token punctuation">,</span> msg<span class="token punctuation">.</span><span class="token function">GetTitle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> msg<span class="token punctuation">.</span><span class="token function">GetContent</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">				<span class="token punctuation">}</span></span>
<span class="line">			<span class="token punctuation">}</span></span>
<span class="line">		<span class="token punctuation">}</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">return</span> <span class="token operator">&amp;</span>internalMessageV1<span class="token punctuation">.</span>SendMessageResponse<span class="token punctuation">{</span></span>
<span class="line">		MessageId<span class="token punctuation">:</span> msg<span class="token punctuation">.</span><span class="token function">GetId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">	<span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token boolean">nil</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// sendNotification 向客户端发送通知消息</span></span>
<span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>s <span class="token operator">*</span>InternalMessageService<span class="token punctuation">)</span> <span class="token function">sendNotification</span><span class="token punctuation">(</span>ctx context<span class="token punctuation">.</span>Context<span class="token punctuation">,</span> messageId <span class="token builtin">uint32</span><span class="token punctuation">,</span> recipientUserId <span class="token builtin">uint32</span><span class="token punctuation">,</span> senderUserId <span class="token builtin">uint32</span><span class="token punctuation">,</span> now <span class="token operator">*</span>time<span class="token punctuation">.</span>Time<span class="token punctuation">,</span> title<span class="token punctuation">,</span> content <span class="token builtin">string</span><span class="token punctuation">)</span> <span class="token builtin">error</span> <span class="token punctuation">{</span></span>
<span class="line">	recipient <span class="token operator">:=</span> <span class="token operator">&amp;</span>internalMessageV1<span class="token punctuation">.</span>InternalMessageRecipient<span class="token punctuation">{</span></span>
<span class="line">		MessageId<span class="token punctuation">:</span>       trans<span class="token punctuation">.</span><span class="token function">Ptr</span><span class="token punctuation">(</span>messageId<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">		RecipientUserId<span class="token punctuation">:</span> trans<span class="token punctuation">.</span><span class="token function">Ptr</span><span class="token punctuation">(</span>recipientUserId<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">		Status<span class="token punctuation">:</span>          trans<span class="token punctuation">.</span><span class="token function">Ptr</span><span class="token punctuation">(</span>internalMessageV1<span class="token punctuation">.</span>InternalMessageRecipient_SENT<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">		CreatedBy<span class="token punctuation">:</span>       trans<span class="token punctuation">.</span><span class="token function">Ptr</span><span class="token punctuation">(</span>senderUserId<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">		CreatedAt<span class="token punctuation">:</span>       timeutil<span class="token punctuation">.</span><span class="token function">TimeToTimestamppb</span><span class="token punctuation">(</span>now<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">		Title<span class="token punctuation">:</span>           trans<span class="token punctuation">.</span><span class="token function">Ptr</span><span class="token punctuation">(</span>title<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">		Content<span class="token punctuation">:</span>         trans<span class="token punctuation">.</span><span class="token function">Ptr</span><span class="token punctuation">(</span>content<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">var</span> err <span class="token builtin">error</span></span>
<span class="line">	<span class="token keyword">var</span> entity <span class="token operator">*</span>internalMessageV1<span class="token punctuation">.</span>InternalMessageRecipient</span>
<span class="line">	<span class="token keyword">if</span> entity<span class="token punctuation">,</span> err <span class="token operator">=</span> s<span class="token punctuation">.</span>internalMessageRecipientRepo<span class="token punctuation">.</span><span class="token function">Create</span><span class="token punctuation">(</span>ctx<span class="token punctuation">,</span> recipient<span class="token punctuation">)</span><span class="token punctuation">;</span> err <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span></span>
<span class="line">		s<span class="token punctuation">.</span>log<span class="token punctuation">.</span><span class="token function">Errorf</span><span class="token punctuation">(</span><span class="token string">"send message failed, send to user failed, %s"</span><span class="token punctuation">,</span> err<span class="token punctuation">)</span></span>
<span class="line">		<span class="token keyword">return</span> err</span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line">	recipient<span class="token punctuation">.</span>Id <span class="token operator">=</span> entity<span class="token punctuation">.</span>Id</span>
<span class="line"></span>
<span class="line">	recipientJson<span class="token punctuation">,</span> <span class="token boolean">_</span> <span class="token operator">:=</span> json<span class="token punctuation">.</span><span class="token function">Marshal</span><span class="token punctuation">(</span>recipient<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">	recipientStreamIds <span class="token operator">:=</span> s<span class="token punctuation">.</span>userToken<span class="token punctuation">.</span><span class="token function">GetAccessToken</span><span class="token punctuation">(</span>ctx<span class="token punctuation">,</span> recipientUserId<span class="token punctuation">)</span></span>
<span class="line">	<span class="token keyword">for</span> <span class="token boolean">_</span><span class="token punctuation">,</span> streamId <span class="token operator">:=</span> <span class="token keyword">range</span> recipientStreamIds <span class="token punctuation">{</span></span>
<span class="line">		s<span class="token punctuation">.</span>sseServer<span class="token punctuation">.</span><span class="token function">Publish</span><span class="token punctuation">(</span>ctx<span class="token punctuation">,</span> sse<span class="token punctuation">.</span><span class="token function">StreamID</span><span class="token punctuation">(</span>streamId<span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token operator">&amp;</span>sse<span class="token punctuation">.</span>Event<span class="token punctuation">{</span></span>
<span class="line">			ID<span class="token punctuation">:</span>    <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token function">byte</span><span class="token punctuation">(</span>uuid<span class="token punctuation">.</span><span class="token function">New</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">String</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">			Data<span class="token punctuation">:</span>  recipientJson<span class="token punctuation">,</span></span>
<span class="line">			Event<span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token function">byte</span><span class="token punctuation">(</span><span class="token string">"notification"</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">		<span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">return</span> <span class="token boolean">nil</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="三、api-接口设计与使用​" tabindex="-1"><a class="header-anchor" href="#三、api-接口设计与使用​"><span>三、API 接口设计与使用​</span></a></h2>
<p>Go Wind Admin 站内信模块提供 RESTful 风格 API，基于 ProtoBuf 定义接口规范，支持跨语言调用。​</p>
<h3 id="_3-1-核心-api-列表-proto-定义-​" tabindex="-1"><a class="header-anchor" href="#_3-1-核心-api-列表-proto-定义-​"><span>3.1 核心 API 列表（Proto 定义）​</span></a></h3>
<div class="language-protobuf line-numbers-mode" data-highlighter="prismjs" data-ext="protobuf"><pre v-pre><code><span class="line"><span class="token comment">// api/protos/admin/service/v1/i_internal_message.proto</span></span>
<span class="line"><span class="token keyword">syntax</span> <span class="token operator">=</span> <span class="token string">"proto3"</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">package</span> admin<span class="token punctuation">.</span><span class="token keyword">service</span><span class="token punctuation">.</span>v1<span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">import</span> <span class="token string">"gnostic/openapi/v3/annotations.proto"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token string">"google/api/annotations.proto"</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token string">"google/protobuf/empty.proto"</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">import</span> <span class="token string">"pagination/v1/pagination.proto"</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">import</span> <span class="token string">"internal_message/service/v1/internal_message.proto"</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 站内信消息管理服务</span></span>
<span class="line"><span class="token keyword">service</span> <span class="token class-name">InternalMessageService</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token comment">// 查询站内信消息列表</span></span>
<span class="line">  <span class="token keyword">rpc</span> <span class="token function">ListMessage</span><span class="token punctuation">(</span><span class="token class-name">pagination.PagingRequest</span><span class="token punctuation">)</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token class-name">internal_message.service.v1.ListInternalMessageResponse</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">option</span> <span class="token punctuation">(</span>google<span class="token punctuation">.</span>api<span class="token punctuation">.</span>http<span class="token punctuation">)</span> <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">      get<span class="token punctuation">:</span> <span class="token string">"/admin/v1/internal-message/messages"</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token comment">// 查询站内信消息详情</span></span>
<span class="line">  <span class="token keyword">rpc</span> <span class="token function">GetMessage</span><span class="token punctuation">(</span><span class="token class-name">internal_message.service.v1.GetInternalMessageRequest</span><span class="token punctuation">)</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token class-name">internal_message.service.v1.InternalMessage</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">option</span> <span class="token punctuation">(</span>google<span class="token punctuation">.</span>api<span class="token punctuation">.</span>http<span class="token punctuation">)</span> <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">      get<span class="token punctuation">:</span> <span class="token string">"/admin/v1/internal-message/messages/{id}"</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token comment">// 更新站内信消息</span></span>
<span class="line">  <span class="token keyword">rpc</span> <span class="token function">UpdateMessage</span><span class="token punctuation">(</span><span class="token class-name">internal_message.service.v1.UpdateInternalMessageRequest</span><span class="token punctuation">)</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token class-name">google.protobuf.Empty</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">option</span> <span class="token punctuation">(</span>google<span class="token punctuation">.</span>api<span class="token punctuation">.</span>http<span class="token punctuation">)</span> <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">      put<span class="token punctuation">:</span> <span class="token string">"/admin/v1/internal-message/messages/{data.id}"</span></span>
<span class="line">      body<span class="token punctuation">:</span> <span class="token string">"*"</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token comment">// 删除站内信消息</span></span>
<span class="line">  <span class="token keyword">rpc</span> <span class="token function">DeleteMessage</span><span class="token punctuation">(</span><span class="token class-name">internal_message.service.v1.DeleteInternalMessageRequest</span><span class="token punctuation">)</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token class-name">google.protobuf.Empty</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">option</span> <span class="token punctuation">(</span>google<span class="token punctuation">.</span>api<span class="token punctuation">.</span>http<span class="token punctuation">)</span> <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">      delete<span class="token punctuation">:</span> <span class="token string">"/admin/v1/internal-message/messages/{id}"</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line">  <span class="token comment">// 发送消息</span></span>
<span class="line">  <span class="token keyword">rpc</span> <span class="token function">SendMessage</span><span class="token punctuation">(</span><span class="token class-name">internal_message.service.v1.SendMessageRequest</span><span class="token punctuation">)</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token class-name">internal_message.service.v1.SendMessageResponse</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">option</span> <span class="token punctuation">(</span>google<span class="token punctuation">.</span>api<span class="token punctuation">.</span>http<span class="token punctuation">)</span> <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">      post<span class="token punctuation">:</span> <span class="token string">"/admin/v1/internal-message/send"</span></span>
<span class="line">      body<span class="token punctuation">:</span> <span class="token string">"*"</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token comment">// 获取用户的收件箱列表 (通知类)</span></span>
<span class="line">  <span class="token keyword">rpc</span> <span class="token function">ListUserInbox</span><span class="token punctuation">(</span><span class="token class-name">pagination.PagingRequest</span><span class="token punctuation">)</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token class-name">internal_message.service.v1.ListUserInboxResponse</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">option</span> <span class="token punctuation">(</span>google<span class="token punctuation">.</span>api<span class="token punctuation">.</span>http<span class="token punctuation">)</span> <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">      get<span class="token punctuation">:</span> <span class="token string">"/admin/v1/internal-message/inbox"</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token comment">// 删除用户收件箱中的通知记录</span></span>
<span class="line">  <span class="token keyword">rpc</span> <span class="token function">DeleteNotificationFromInbox</span><span class="token punctuation">(</span><span class="token class-name">internal_message.service.v1.DeleteNotificationFromInboxRequest</span><span class="token punctuation">)</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token class-name">google.protobuf.Empty</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">option</span> <span class="token punctuation">(</span>google<span class="token punctuation">.</span>api<span class="token punctuation">.</span>http<span class="token punctuation">)</span> <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">      post<span class="token punctuation">:</span> <span class="token string">"/admin/v1/internal-message/inbox/delete"</span></span>
<span class="line">      body<span class="token punctuation">:</span> <span class="token string">"*"</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token comment">// 将通知标记为已读</span></span>
<span class="line">  <span class="token keyword">rpc</span> <span class="token function">MarkNotificationAsRead</span><span class="token punctuation">(</span><span class="token class-name">internal_message.service.v1.MarkNotificationAsReadRequest</span><span class="token punctuation">)</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token class-name">google.protobuf.Empty</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">option</span> <span class="token punctuation">(</span>google<span class="token punctuation">.</span>api<span class="token punctuation">.</span>http<span class="token punctuation">)</span> <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">      post<span class="token punctuation">:</span> <span class="token string">"/admin/v1/internal-message/read"</span></span>
<span class="line">      body<span class="token punctuation">:</span> <span class="token string">"*"</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token comment">// 撤销某条消息</span></span>
<span class="line">  <span class="token keyword">rpc</span> <span class="token function">RevokeMessage</span><span class="token punctuation">(</span><span class="token class-name">internal_message.service.v1.RevokeMessageRequest</span><span class="token punctuation">)</span> <span class="token keyword">returns</span> <span class="token punctuation">(</span><span class="token class-name">google.protobuf.Empty</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">option</span> <span class="token punctuation">(</span>google<span class="token punctuation">.</span>api<span class="token punctuation">.</span>http<span class="token punctuation">)</span> <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">      post<span class="token punctuation">:</span> <span class="token string">"/admin/v1/internal-message/revoke"</span></span>
<span class="line">      body<span class="token punctuation">:</span> <span class="token string">"*"</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_3-2-api-调用示例-curl-​" tabindex="-1"><a class="header-anchor" href="#_3-2-api-调用示例-curl-​"><span>3.2 API 调用示例（curl）​</span></a></h3>
<h4 id="_1-发送系统通知​" tabindex="-1"><a class="header-anchor" href="#_1-发送系统通知​"><span>（1）发送系统通知​</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code><span class="line"><span class="token function">curl</span> <span class="token parameter variable">-X</span> POST http://127.0.0.1:8000/api/v1/internal-message/send <span class="token punctuation">\</span>​</span>
<span class="line"><span class="token parameter variable">-H</span> <span class="token string">"Content-Type: application/json"</span> <span class="token punctuation">\</span>​</span>
<span class="line"><span class="token parameter variable">-H</span> <span class="token string">"Authorization: Bearer {admin_token}"</span> <span class="token punctuation">\</span>​</span>
<span class="line"><span class="token parameter variable">-d</span> <span class="token string">'{​</span>
<span class="line">    "type": "NOTIFICATION",</span>
<span class="line">    "recipientUserId": 0,</span>
<span class="line">    "conversationId": 0,</span>
<span class="line">    "categoryId": 0,</span>
<span class="line">    "targetAll": true,</span>
<span class="line">    "title": "账号权限更新",​</span>
<span class="line">    "content": "您的账号已添加「订单审核」权限，生效时间：2024-10-01",</span>
<span class="line">}'</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>响应结果：​</p>
<div class="language-json line-numbers-mode" data-highlighter="prismjs" data-ext="json"><pre v-pre><code><span class="line"><span class="token punctuation">{</span></span>
<span class="line">  <span class="token property">"messageId"</span><span class="token operator">:</span> <span class="token number">0</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="四、前端对接" tabindex="-1"><a class="header-anchor" href="#四、前端对接"><span>四、前端对接</span></a></h2>
<p>在站内信功能中，「实时性」是提升用户体验的关键 —— 用户无需刷新页面，就能即时收到新消息提醒。这段代码基于 SSE（Server-Sent Events，服务器发送事件） 实现前端实时通知接收，适配 Go Wind Admin 后端的推送能力。</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token comment">// apps/admin/src/layouts/basic.vue</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">function</span> <span class="token function">handleSseNotification</span><span class="token punctuation">(</span></span>
<span class="line">  data<span class="token operator">:</span> InternalMessageRecipient<span class="token punctuation">,</span></span>
<span class="line">  event<span class="token operator">:</span> MessageEvent<span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'SSE'</span><span class="token punctuation">,</span> event<span class="token punctuation">,</span> data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span><span class="token function">hasMessage</span><span class="token punctuation">(</span>data<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    notifications<span class="token punctuation">.</span>value<span class="token punctuation">.</span><span class="token function">unshift</span><span class="token punctuation">(</span><span class="token function">convertInternalMessageRecipient</span><span class="token punctuation">(</span>data<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">function</span> <span class="token function">initSseClient</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token keyword">const</span> targetSseUrl <span class="token operator">=</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token keyword">import</span><span class="token punctuation">.</span>meta<span class="token punctuation">.</span>env<span class="token punctuation">.</span><span class="token constant">VITE_GLOB_SSE_URL</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">?stream=</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token function">encodeURIComponent</span><span class="token punctuation">(</span>accessStore<span class="token punctuation">.</span>accessToken<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token keyword">const</span> sseClient <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">SSEClient</span><span class="token punctuation">(</span><span class="token punctuation">{</span></span>
<span class="line">    url<span class="token operator">:</span> targetSseUrl<span class="token punctuation">,</span></span>
<span class="line">    withCredentials<span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  sseClient<span class="token punctuation">.</span><span class="token function">connect</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  sseClient<span class="token punctuation">.</span><span class="token generic-function"><span class="token function">on</span><span class="token generic class-name"><span class="token operator">&lt;</span>InternalMessageRecipient<span class="token operator">></span></span></span><span class="token punctuation">(</span><span class="token string">'notification'</span><span class="token punctuation">,</span> handleSseNotification<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="五、总结与展望​" tabindex="-1"><a class="header-anchor" href="#五、总结与展望​"><span>五、总结与展望​</span></a></h2>
<p>Go Wind Admin 站内信模块通过「标准化数据模型 + 封装核心逻辑 + 开放 API 接口」，实现了「开箱即用」的特性，开发者无需关注底层存储与流程设计，仅需通过 API 即可快速集成。目前模块已支持消息发送、读取、过期清理等基础功能，未来将进一步优化：​</p>
<ul>
<li>新增消息撤回功能（支持发送后 N 分钟内撤回）；​</li>
<li>支持消息标签（如「重要」「工作」），提升筛选效率；​</li>
<li>集成消息搜索（基于 Elasticsearch），支持全文检索。​</li>
</ul>
<p>若你在使用过程中遇到问题，可通过 Go Wind Admin 官方 <a href="https://github.com/tx7do/go-wind-admin" target="_blank" rel="noopener noreferrer">GitHub</a> 提交 Issue，或参与社区讨论获取支持。</p>
<h2 id="项目代码" tabindex="-1"><a class="header-anchor" href="#项目代码"><span>项目代码</span></a></h2>
<ul>
<li><a href="https://gitee.com/tx7do/go-wind-admin" target="_blank" rel="noopener noreferrer">go-wind-admin Gitee</a></li>
<li><a href="https://github.com/tx7do/go-wind-admin" target="_blank" rel="noopener noreferrer">go-wind-admin Github</a></li>
</ul>
<h2 id="参考资料" tabindex="-1"><a class="header-anchor" href="#参考资料"><span>参考资料</span></a></h2>
<ul>
<li><a href="https://www.woshipm.com/pd/1006719.html" target="_blank" rel="noopener noreferrer">简单聊聊，如何设计站内信？</a></li>
</ul>
</div></template>


