<template><div><h1 id="基于-go-kratos-与-mcp-的推荐服务实战指南" tabindex="-1"><a class="header-anchor" href="#基于-go-kratos-与-mcp-的推荐服务实战指南"><span>基于 Go-Kratos 与 MCP 的推荐服务实战指南</span></a></h1>
<p>在微服务与多模块协同场景下，实现服务间的标准化通信与流程调度是核心挑战。本文聚焦 <code v-pre>go-kratos-mcp-demo</code> 项目，讲解如何基于
<code v-pre>Go-Kratos</code> 框架与 <code v-pre>MCP</code>（模块化协同协议）构建可扩展的推荐服务，涵盖服务契约设计（proto）、模块化流程编排、召回/过滤/排序等关键模块的实现与测试，并展示实战部署与可观测性方案。</p>
<h2 id="技术基石-go-kratos-与-mcp-的协同架构" tabindex="-1"><a class="header-anchor" href="#技术基石-go-kratos-与-mcp-的协同架构"><span>技术基石：Go-Kratos 与 MCP 的协同架构</span></a></h2>
<p>项目技术选型围绕 “模块化协同” 核心需求展开，<code v-pre>Go-Kratos</code> 与 <code v-pre>MCP</code> 构成架构的两大支柱，形成 “框架赋能 + 协议规范” 的协同模式：</p>
<ul>
<li><strong>Go-Kratos：</strong> 作为B站开源的微服务框架，提供了从 API 定义、配置管理到服务治理的全链路支持。项目通过其 <code v-pre>transport</code> 层扩展 <code v-pre>kratos-transport</code> 实现了 MCP 协议的集成，同时借助 wire 依赖注入工具简化了服务间依赖管理，让模块解耦更彻底。</li>
<li><strong>MCP 协议：</strong> 通过 <code v-pre>mcp-go</code> 库实现多模块协同，定义了标准化的工具注册、请求参数与响应格式。在推荐流程中，召回、排序、过滤模块通过 MCP 上下文传递数据，避免了硬编码耦合，使各模块可独立升级与复用。</li>
</ul>
<p>从依赖管理可见，项目通过 <code v-pre>github.com/tx7do/kratos-transport/transport/mcp</code> 实现了 Kratos 与 MCP 的无缝对接，同时引入 <code v-pre>mcp-go</code> 提供协议核心能力，形成了 &quot;框架 + 协议&quot; 的协同开发模式。</p>
<h2 id="mcp-服务设计-基于-kratos-的模块化调度实现" tabindex="-1"><a class="header-anchor" href="#mcp-服务设计-基于-kratos-的模块化调度实现"><span>MCP 服务设计：基于 Kratos 的模块化调度实现</span></a></h2>
<h3 id="_1-mcp-服务初始化与工具注册" tabindex="-1"><a class="header-anchor" href="#_1-mcp-服务初始化与工具注册"><span>1. MCP 服务初始化与工具注册</span></a></h3>
<p>在 <code v-pre>internal/server/mcp.go</code> 中，项目基于 <code v-pre>Kratos</code> 扩展的 <code v-pre>mcpServer</code> 构建 <code v-pre>MCP</code> 服务，核心是注册 &quot;推荐工具&quot; 并绑定处理逻辑：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go"><pre v-pre><code><span class="line"><span class="token keyword">func</span> <span class="token function">NewMcpServer</span><span class="token punctuation">(</span><span class="token boolean">_</span> log<span class="token punctuation">.</span>Logger<span class="token punctuation">,</span> recommendService <span class="token operator">*</span>service<span class="token punctuation">.</span>RecommendService<span class="token punctuation">)</span> <span class="token operator">*</span>mcpServer<span class="token punctuation">.</span>Server <span class="token punctuation">{</span></span>
<span class="line">    srv <span class="token operator">:=</span> mcpServer<span class="token punctuation">.</span><span class="token function">NewServer</span><span class="token punctuation">(</span></span>
<span class="line">        mcpServer<span class="token punctuation">.</span><span class="token function">WithServerName</span><span class="token punctuation">(</span><span class="token string">"Recommend MCP Server"</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">        mcpServer<span class="token punctuation">.</span><span class="token function">WithMCPServeAddress</span><span class="token punctuation">(</span><span class="token string">":8080"</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token comment">// MCP 服务端口</span></span>
<span class="line">        <span class="token comment">// 更多配置...</span></span>
<span class="line">    <span class="token punctuation">)</span></span>
<span class="line">    </span>
<span class="line">    <span class="token comment">// 注册推荐工具，定义输入参数schema</span></span>
<span class="line">    <span class="token keyword">if</span> err <span class="token operator">=</span> srv<span class="token punctuation">.</span><span class="token function">RegisterHandler</span><span class="token punctuation">(</span></span>
<span class="line">        mcp<span class="token punctuation">.</span>Tool<span class="token punctuation">{</span></span>
<span class="line">            Name<span class="token punctuation">:</span>        <span class="token string">"recommend"</span><span class="token punctuation">,</span></span>
<span class="line">            Description<span class="token punctuation">:</span> <span class="token string">"获取个性化推荐结果"</span><span class="token punctuation">,</span></span>
<span class="line">            InputSchema<span class="token punctuation">:</span> mcp<span class="token punctuation">.</span>ToolInputSchema<span class="token punctuation">{</span> <span class="token comment">// MCP 标准化输入定义</span></span>
<span class="line">                Type<span class="token punctuation">:</span> <span class="token string">"object"</span><span class="token punctuation">,</span></span>
<span class="line">                Properties<span class="token punctuation">:</span> <span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token keyword">interface</span><span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">{</span></span>
<span class="line">                    <span class="token string">"userFeature"</span><span class="token punctuation">:</span> <span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token keyword">interface</span><span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">{</span> <span class="token comment">// 用户特征</span></span>
<span class="line">                        <span class="token string">"type"</span><span class="token punctuation">:</span> <span class="token string">"object"</span><span class="token punctuation">,</span></span>
<span class="line">                        <span class="token string">"properties"</span><span class="token punctuation">:</span> <span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token keyword">interface</span><span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">{</span></span>
<span class="line">                            <span class="token string">"userId"</span><span class="token punctuation">:</span> <span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token keyword">interface</span><span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">{</span><span class="token string">"type"</span><span class="token punctuation">:</span> <span class="token string">"string"</span><span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">                        <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">                    <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">                    <span class="token string">"triggerItemId"</span><span class="token punctuation">:</span> <span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token keyword">interface</span><span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">{</span><span class="token string">"type"</span><span class="token punctuation">:</span> <span class="token string">"integer"</span><span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token comment">// 触发商品ID</span></span>
<span class="line">                    <span class="token string">"scene"</span><span class="token punctuation">:</span>         <span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token keyword">interface</span><span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">{</span><span class="token string">"type"</span><span class="token punctuation">:</span> <span class="token string">"string"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>  <span class="token comment">// 推荐场景</span></span>
<span class="line">                <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">                Required<span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token builtin">string</span><span class="token punctuation">{</span><span class="token string">"userFeature"</span><span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">        recommendService<span class="token punctuation">.</span>HandleRecommend<span class="token punctuation">,</span> <span class="token comment">// 绑定处理函数</span></span>
<span class="line">    <span class="token punctuation">)</span><span class="token punctuation">;</span> err <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span></span>
<span class="line">        log<span class="token punctuation">.</span><span class="token function">Errorf</span><span class="token punctuation">(</span><span class="token string">"failed to register recommend tool: %v"</span><span class="token punctuation">,</span> err<span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    </span>
<span class="line">    <span class="token keyword">return</span> srv</span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这段代码体现了 MCP 协议的核心思想：通过标准化的工具定义（名称、输入 schema、描述），使调用方无需关心具体实现，只需按协议格式请求即可。而 Kratos 的服务管理能力则确保了 MCP 服务的高可用启动与配置加载。</p>
<h3 id="_2-多模块协同流程-mcp-上下文驱动的推荐链路" tabindex="-1"><a class="header-anchor" href="#_2-多模块协同流程-mcp-上下文驱动的推荐链路"><span>2. 多模块协同流程：MCP 上下文驱动的推荐链路</span></a></h3>
<p>推荐服务的核心逻辑在 <code v-pre>internal/service/recommend.go</code> 中实现，通过 <code v-pre>MCP</code> 上下文串联 <strong>召回</strong>、<strong>排序</strong>、<strong>过滤</strong> 三大模块：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go"><pre v-pre><code><span class="line"><span class="token comment">// HandleRecommend MCP协议推荐处理入口</span></span>
<span class="line"><span class="token keyword">func</span> <span class="token punctuation">(</span>s <span class="token operator">*</span>RecommendService<span class="token punctuation">)</span> <span class="token function">HandleRecommend</span><span class="token punctuation">(</span>ctx context<span class="token punctuation">.</span>Context<span class="token punctuation">,</span> request mcp<span class="token punctuation">.</span>CallToolRequest<span class="token punctuation">)</span> <span class="token punctuation">(</span><span class="token operator">*</span>mcp<span class="token punctuation">.</span>CallToolResult<span class="token punctuation">,</span> <span class="token builtin">error</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// 1. 解析MCP请求参数为内部上下文</span></span>
<span class="line">    <span class="token keyword">var</span> actionCtx recommendV1<span class="token punctuation">.</span>UserActionContext</span>
<span class="line">    <span class="token keyword">if</span> err <span class="token operator">:=</span> codec<span class="token punctuation">.</span><span class="token function">Unmarshal</span><span class="token punctuation">(</span>argsData<span class="token punctuation">,</span> <span class="token operator">&amp;</span>actionCtx<span class="token punctuation">)</span><span class="token punctuation">;</span> err <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token keyword">return</span> <span class="token boolean">nil</span><span class="token punctuation">,</span> err</span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    </span>
<span class="line">    <span class="token comment">// 2. 生成请求ID，用于全链路追踪</span></span>
<span class="line">    requestId <span class="token operator">:=</span> uuid<span class="token punctuation">.</span><span class="token function">New</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">String</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    </span>
<span class="line">    <span class="token comment">// 3. 召回模块：基于用户历史与场景召回候选物品</span></span>
<span class="line">    recallInput <span class="token operator">:=</span> <span class="token operator">&amp;</span>recommendV1<span class="token punctuation">.</span>RecallInputContext<span class="token punctuation">{</span></span>
<span class="line">        Stage<span class="token punctuation">:</span>          recommendV1<span class="token punctuation">.</span>ContextStage_CONTEXT_STAGE_RECALL<span class="token punctuation">,</span></span>
<span class="line">        RequestId<span class="token punctuation">:</span>      requestId<span class="token punctuation">,</span></span>
<span class="line">        UserFeature<span class="token punctuation">:</span>    actionCtx<span class="token punctuation">.</span><span class="token function">GetUserFeature</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">        HistoryItemIds<span class="token punctuation">:</span> history<span class="token punctuation">,</span> <span class="token comment">// 用户历史行为</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    recallOutput<span class="token punctuation">,</span> err <span class="token operator">:=</span> s<span class="token punctuation">.</span>recallService<span class="token punctuation">.</span><span class="token function">Recall</span><span class="token punctuation">(</span>ctx<span class="token punctuation">,</span> recallInput<span class="token punctuation">)</span></span>
<span class="line">    </span>
<span class="line">    <span class="token comment">// 4. 排序模块：对召回结果打分排序</span></span>
<span class="line">    rankInput <span class="token operator">:=</span> <span class="token operator">&amp;</span>recommendV1<span class="token punctuation">.</span>RankInputContext<span class="token punctuation">{</span></span>
<span class="line">        Stage<span class="token punctuation">:</span>     recommendV1<span class="token punctuation">.</span>ContextStage_CONTEXT_STAGE_RANK<span class="token punctuation">,</span></span>
<span class="line">        RequestId<span class="token punctuation">:</span> requestId<span class="token punctuation">,</span></span>
<span class="line">        RecallCtx<span class="token punctuation">:</span> recallOutput<span class="token punctuation">,</span> <span class="token comment">// 传递召回结果</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    rankOutput<span class="token punctuation">,</span> err <span class="token operator">:=</span> s<span class="token punctuation">.</span>rankService<span class="token punctuation">.</span><span class="token function">Rank</span><span class="token punctuation">(</span>ctx<span class="token punctuation">,</span> rankInput<span class="token punctuation">)</span></span>
<span class="line">    </span>
<span class="line">    <span class="token comment">// 5. 过滤模块：过滤黑名单与已购物品</span></span>
<span class="line">    filterInput <span class="token operator">:=</span> <span class="token operator">&amp;</span>recommendV1<span class="token punctuation">.</span>FilterInputContext<span class="token punctuation">{</span></span>
<span class="line">        Stage<span class="token punctuation">:</span>            recommendV1<span class="token punctuation">.</span>ContextStage_CONTEXT_STAGE_FILTER<span class="token punctuation">,</span></span>
<span class="line">        RequestId<span class="token punctuation">:</span>        requestId<span class="token punctuation">,</span></span>
<span class="line">        RankCtx<span class="token punctuation">:</span>          rankOutput<span class="token punctuation">,</span> <span class="token comment">// 传递排序结果</span></span>
<span class="line">        BlacklistItemIds<span class="token punctuation">:</span> s<span class="token punctuation">.</span>filterService<span class="token punctuation">.</span>rc<span class="token punctuation">.</span><span class="token function">GetService</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">GetFilter</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">GetBlacklist</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    finalOutput<span class="token punctuation">,</span> err <span class="token operator">:=</span> s<span class="token punctuation">.</span>filterService<span class="token punctuation">.</span><span class="token function">Filter</span><span class="token punctuation">(</span>ctx<span class="token punctuation">,</span> filterInput<span class="token punctuation">)</span></span>
<span class="line">    </span>
<span class="line">    <span class="token comment">// 6. 封装为MCP响应格式</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token operator">&amp;</span>mcp<span class="token punctuation">.</span>CallToolResult<span class="token punctuation">{</span></span>
<span class="line">        Content<span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>mcp<span class="token punctuation">.</span>Content<span class="token punctuation">{</span></span>
<span class="line">            mcp<span class="token punctuation">.</span>TextContent<span class="token punctuation">{</span>Type<span class="token punctuation">:</span> <span class="token string">"text"</span><span class="token punctuation">,</span> Text<span class="token punctuation">:</span> <span class="token function">string</span><span class="token punctuation">(</span>finalOutputJson<span class="token punctuation">)</span><span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token boolean">nil</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>整个流程中，MCP 协议承担了 &quot;标准化胶水&quot; 的角色：输入参数通过 <code v-pre>MCP</code> 定义的 <code v-pre>CallToolRequest</code> 传递，各模块通过上下文（<code v-pre>RecallInputContext</code>、<code v-pre>RankInputContext</code> 等）共享数据，最终结果以 <code v-pre>CallToolResult</code> 标准化返回。而 Kratos 的依赖注入（通过 <code v-pre>wire</code>）则确保了 <code v-pre>recallService</code>、<code v-pre>rankService</code> 等模块的灵活注入，实现了解耦。</p>
<h2 id="服务部署与测试-kratos-生态工具链的实践" tabindex="-1"><a class="header-anchor" href="#服务部署与测试-kratos-生态工具链的实践"><span>服务部署与测试：Kratos 生态工具链的实践</span></a></h2>
<p>项目借助 Kratos 生态的工具链实现了标准化的构建与测试流程：</p>
<h3 id="_1-服务启动" tabindex="-1"><a class="header-anchor" href="#_1-服务启动"><span>1. 服务启动</span></a></h3>
<p>在 <code v-pre>cmd/server/main.go</code> 中，通过 <code v-pre>Kratos</code> 的 <code v-pre>kratos.New</code> 整合 <code v-pre>MCP服务</code> 与 <code v-pre>HTTP服务</code>，实现多协议共存：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go"><pre v-pre><code><span class="line">app <span class="token operator">:=</span> kratos<span class="token punctuation">.</span><span class="token function">New</span><span class="token punctuation">(</span></span>
<span class="line">    kratos<span class="token punctuation">.</span><span class="token function">Name</span><span class="token punctuation">(</span><span class="token string">"recommend-mcp-server"</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    kratos<span class="token punctuation">.</span><span class="token function">Server</span><span class="token punctuation">(</span></span>
<span class="line">        ms<span class="token punctuation">,</span> <span class="token comment">// MCP服务</span></span>
<span class="line">        hs<span class="token punctuation">,</span> <span class="token comment">// HTTP服务</span></span>
<span class="line">    <span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-测试支持" tabindex="-1"><a class="header-anchor" href="#_2-测试支持"><span>2. 测试支持</span></a></h3>
<p><code v-pre>internal/service/recommend_test.go</code> 中，通过 MCP 客户端模拟请求，验证整个推荐链路：</p>
<div class="language-go line-numbers-mode" data-highlighter="prismjs" data-ext="go"><pre v-pre><code><span class="line"><span class="token comment">// 初始化MCP客户端</span></span>
<span class="line">httpTransport<span class="token punctuation">,</span> <span class="token boolean">_</span> <span class="token operator">:=</span> transport<span class="token punctuation">.</span><span class="token function">NewStreamableHTTP</span><span class="token punctuation">(</span><span class="token string">"http://localhost:8080/mcp"</span><span class="token punctuation">)</span></span>
<span class="line">mcpClient <span class="token operator">:=</span> client<span class="token punctuation">.</span><span class="token function">NewClient</span><span class="token punctuation">(</span>httpTransport<span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 调用推荐工具</span></span>
<span class="line">result<span class="token punctuation">,</span> <span class="token boolean">_</span> <span class="token operator">:=</span> mcpClient<span class="token punctuation">.</span><span class="token function">CallTool</span><span class="token punctuation">(</span>ctx<span class="token punctuation">,</span> mcp<span class="token punctuation">.</span>CallToolRequest<span class="token punctuation">{</span></span>
<span class="line">    Params<span class="token punctuation">:</span> mcp<span class="token punctuation">.</span>CallToolParams<span class="token punctuation">{</span></span>
<span class="line">        Name<span class="token punctuation">:</span> <span class="token string">"recommend"</span><span class="token punctuation">,</span></span>
<span class="line">        Arguments<span class="token punctuation">:</span> <span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token keyword">interface</span><span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">{</span></span>
<span class="line">            <span class="token string">"userFeature"</span><span class="token punctuation">:</span> <span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token keyword">interface</span><span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">{</span><span class="token string">"userId"</span><span class="token punctuation">:</span> <span class="token string">"user123"</span><span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token string">"triggerItemId"</span><span class="token punctuation">:</span> <span class="token function">int64</span><span class="token punctuation">(</span><span class="token number">1001</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token string">"scene"</span><span class="token punctuation">:</span>         <span class="token string">"homepage"</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_3-构建脚本" tabindex="-1"><a class="header-anchor" href="#_3-构建脚本"><span>3. 构建脚本</span></a></h3>
<p><code v-pre>Makefile</code> 整合了 <code v-pre>Kratos</code> 推荐的开发流程，支持一键生成 API 代码、启动服务：</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code><span class="line"><span class="token comment"># 生成API与OpenAPI文档</span></span>
<span class="line"><span class="token function">make</span> api openapi</span>
<span class="line"></span>
<span class="line"><span class="token comment"># 生成依赖注入代码</span></span>
<span class="line"><span class="token function">make</span> wire</span>
<span class="line"></span>
<span class="line"><span class="token comment"># 启动服务（同时启动MCP与HTTP服务）</span></span>
<span class="line"><span class="token function">make</span> run</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="总结-go-kratos-与-mcp-协同的价值" tabindex="-1"><a class="header-anchor" href="#总结-go-kratos-与-mcp-协同的价值"><span>总结：Go-Kratos 与 MCP 协同的价值</span></a></h2>
<p><code v-pre>go-kratos-mcp-demo</code> 项目展示了 <code v-pre>Go-Kratos</code> 与 <code v-pre>MCP协议</code> 在模块化服务开发中的协同优势，为微服务架构设计提供三大启示：</p>
<ol>
<li><strong>标准化协同：</strong> MCP 协议定义了模块间通信的统一规范，使召回、排序等模块可独立开发、复用与升级。</li>
<li><strong>框架赋能：</strong> Kratos 提供的服务管理、配置加载、依赖注入等能力，降低了 MCP 服务的开发与运维成本。</li>
<li><strong>多协议支持：</strong> 通过 Kratos 的 <code v-pre>transport</code> 扩展，项目同时支持 <code v-pre>MCP</code> 与 <code v-pre>HTTP</code> 协议，满足不同场景的调用需求。</li>
</ol>
<p>对于需要构建模块化、可扩展微服务的场景，这种 &quot;框架 + 协议&quot; 的模式具有重要参考价值，既保证了架构的灵活性，又通过标准化降低系统复杂度，具有较强的实践参考价值。</p>
<h2 id="项目代码" tabindex="-1"><a class="header-anchor" href="#项目代码"><span>项目代码</span></a></h2>
<ul>
<li><a href="https://github.com/tx7do/go-kratos-mcp-demo" target="_blank" rel="noopener noreferrer">go-kratos-mcp-demo Gitee</a></li>
<li><a href="https://gitee.com/tx7do/go-kratos-mcp-demo" target="_blank" rel="noopener noreferrer">go-kratos-mcp-demo Github</a></li>
</ul>
</div></template>


