<template><div><h1 id="ping结果正则表达式解析" tabindex="-1"><a class="header-anchor" href="#ping结果正则表达式解析"><span>Ping结果正则表达式解析</span></a></h1>
<h2 id="windows" tabindex="-1"><a class="header-anchor" href="#windows"><span>Windows</span></a></h2>
<h3 id="ping结果示例" tabindex="-1"><a class="header-anchor" href="#ping结果示例"><span>ping结果示例</span></a></h3>
<p>中文：</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code><span class="line"><span class="token function">ping</span> www.baidu.com <span class="token parameter variable">-n</span> <span class="token number">3</span></span>
<span class="line"></span>
<span class="line">正在 Ping www.a.shifen.com <span class="token punctuation">[</span><span class="token number">120.232</span>.145.185<span class="token punctuation">]</span> 具有 <span class="token number">32</span> 字节的数据:</span>
<span class="line">来自 <span class="token number">120.232</span>.145.185 的回复: 字节<span class="token operator">=</span><span class="token number">32</span> 时间<span class="token operator">=</span>45ms <span class="token assign-left variable">TTL</span><span class="token operator">=</span><span class="token number">49</span></span>
<span class="line">来自 <span class="token number">120.232</span>.145.185 的回复: 字节<span class="token operator">=</span><span class="token number">32</span> 时间<span class="token operator">=</span>627ms <span class="token assign-left variable">TTL</span><span class="token operator">=</span><span class="token number">49</span></span>
<span class="line">来自 <span class="token number">120.232</span>.145.185 的回复: 字节<span class="token operator">=</span><span class="token number">32</span> 时间<span class="token operator">=</span>49ms <span class="token assign-left variable">TTL</span><span class="token operator">=</span><span class="token number">49</span></span>
<span class="line"></span>
<span class="line"><span class="token number">120.232</span>.145.185 的 Ping 统计信息:</span>
<span class="line">    数据包: 已发送 <span class="token operator">=</span> <span class="token number">3</span>，已接收 <span class="token operator">=</span> <span class="token number">3</span>，丢失 <span class="token operator">=</span> <span class="token number">0</span> <span class="token punctuation">(</span><span class="token number">0</span>% 丢失<span class="token punctuation">)</span>，</span>
<span class="line">往返行程的估计时间<span class="token punctuation">(</span>以毫秒为单位<span class="token punctuation">)</span>:</span>
<span class="line">    最短 <span class="token operator">=</span> 45ms，最长 <span class="token operator">=</span> 627ms，平均 <span class="token operator">=</span> 240ms</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>英文：</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code><span class="line"><span class="token function">ping</span> www.paessler.com <span class="token parameter variable">-n</span> <span class="token number">4</span></span>
<span class="line"></span>
<span class="line">Pinging paessler.com <span class="token punctuation">[</span><span class="token number">104.16</span>.182.252<span class="token punctuation">]</span> with <span class="token number">32</span> bytes of data:</span>
<span class="line">Reply from <span class="token number">104.16</span>.182.252: <span class="token assign-left variable">bytes</span><span class="token operator">=</span><span class="token number">32</span> <span class="token assign-left variable">time</span><span class="token operator">=</span>4ms <span class="token assign-left variable">TTL</span><span class="token operator">=</span><span class="token number">57</span></span>
<span class="line">Reply from <span class="token number">104.16</span>.182.252: <span class="token assign-left variable">bytes</span><span class="token operator">=</span><span class="token number">32</span> <span class="token assign-left variable">time</span><span class="token operator">=</span>4ms <span class="token assign-left variable">TTL</span><span class="token operator">=</span><span class="token number">57</span></span>
<span class="line">Reply from <span class="token number">104.16</span>.182.252: <span class="token assign-left variable">bytes</span><span class="token operator">=</span><span class="token number">32</span> <span class="token assign-left variable">time</span><span class="token operator">=</span>4ms <span class="token assign-left variable">TTL</span><span class="token operator">=</span><span class="token number">57</span></span>
<span class="line">Reply from <span class="token number">104.16</span>.182.252: <span class="token assign-left variable">bytes</span><span class="token operator">=</span><span class="token number">32</span> <span class="token assign-left variable">time</span><span class="token operator">=</span>4ms <span class="token assign-left variable">TTL</span><span class="token operator">=</span><span class="token number">57</span></span>
<span class="line"></span>
<span class="line">Ping statistics <span class="token keyword">for</span> <span class="token number">104.16</span>.182.252:</span>
<span class="line">Packets: Sent <span class="token operator">=</span> <span class="token number">4</span>, Received <span class="token operator">=</span> <span class="token number">4</span>, Lost <span class="token operator">=</span> <span class="token number">0</span> <span class="token punctuation">(</span><span class="token number">0</span>% loss<span class="token punctuation">)</span>,</span>
<span class="line">Approximate round trip <span class="token builtin class-name">times</span> <span class="token keyword">in</span> milli-seconds:</span>
<span class="line">Minimum <span class="token operator">=</span> 4ms, Maximum <span class="token operator">=</span> 4ms, Average <span class="token operator">=</span> 4ms</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="获取ttl" tabindex="-1"><a class="header-anchor" href="#获取ttl"><span>获取TTL</span></a></h3>
<p>所有TTL:</p>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line">最短 = (\d+)ms.*最长 = (\d+)ms.*平均 = (\d+)ms|Minimum = (\d+)ms.*Maximum = (\d+)ms.*Average = (\d+)ms</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>最短TTL：</p>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line">最短 = (\d+)ms|Minimum = (\d+)ms</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>最长TTL：</p>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line">最长 = (\d+)ms|Maximum = (\d+)ms</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>平均TTL：</p>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line">平均 = (\d+)ms|Average = (\d+)ms</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="linux" tabindex="-1"><a class="header-anchor" href="#linux"><span>Linux</span></a></h2>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code><span class="line"><span class="token function">ping</span> www.baidu.com <span class="token parameter variable">-c</span> <span class="token number">3</span></span>
<span class="line"></span>
<span class="line">PING www.a.shifen.com <span class="token punctuation">(</span><span class="token number">120.232</span>.145.185<span class="token punctuation">)</span> <span class="token number">56</span><span class="token punctuation">(</span><span class="token number">84</span><span class="token punctuation">)</span> bytes of data.</span>
<span class="line"><span class="token number">64</span> bytes from <span class="token number">120.232</span>.145.185 <span class="token punctuation">(</span><span class="token number">120.232</span>.145.185<span class="token punctuation">)</span>: <span class="token assign-left variable">icmp_seq</span><span class="token operator">=</span><span class="token number">1</span> <span class="token assign-left variable">ttl</span><span class="token operator">=</span><span class="token number">48</span> <span class="token assign-left variable">time</span><span class="token operator">=</span><span class="token number">41.0</span> ms</span>
<span class="line"><span class="token number">64</span> bytes from <span class="token number">120.232</span>.145.185 <span class="token punctuation">(</span><span class="token number">120.232</span>.145.185<span class="token punctuation">)</span>: <span class="token assign-left variable">icmp_seq</span><span class="token operator">=</span><span class="token number">2</span> <span class="token assign-left variable">ttl</span><span class="token operator">=</span><span class="token number">48</span> <span class="token assign-left variable">time</span><span class="token operator">=</span><span class="token number">40.4</span> ms</span>
<span class="line"><span class="token number">64</span> bytes from <span class="token number">120.232</span>.145.185 <span class="token punctuation">(</span><span class="token number">120.232</span>.145.185<span class="token punctuation">)</span>: <span class="token assign-left variable">icmp_seq</span><span class="token operator">=</span><span class="token number">3</span> <span class="token assign-left variable">ttl</span><span class="token operator">=</span><span class="token number">48</span> <span class="token assign-left variable">time</span><span class="token operator">=</span><span class="token number">129</span> ms</span>
<span class="line"></span>
<span class="line">--- www.a.shifen.com <span class="token function">ping</span> statistics ---</span>
<span class="line"><span class="token number">3</span> packets transmitted, <span class="token number">3</span> received, <span class="token number">0</span>% packet loss, <span class="token function">time</span> 2156ms</span>
<span class="line">rtt min/avg/max/mdev <span class="token operator">=</span> <span class="token number">40.443</span>/70.028/128.681/41.474 ms</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>获取TTL：</p>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line">rtt\s+min\/avg\/max\/mdev\s+=\s+([0-9]+\.[0-9]+)\/([0-9]+\.[0-9]+)\/([0-9]+\.[0-9]+)\/([0-9]+\.[0-9]+)\s+ms</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></div></template>


