<template><div><h1 id="postgresql按时间分组统计查询-年月日周时分秒" tabindex="-1"><a class="header-anchor" href="#postgresql按时间分组统计查询-年月日周时分秒"><span>Postgresql按时间分组统计查询（年月日周时分秒）</span></a></h1>
<div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code><span class="line"><span class="token keyword">create</span> <span class="token keyword">table</span> <span class="token keyword">public</span><span class="token punctuation">.</span><span class="token string">"user"</span> <span class="token punctuation">(</span></span>
<span class="line">  id <span class="token keyword">integer</span> <span class="token keyword">primary</span> <span class="token keyword">key</span> <span class="token operator">not</span> <span class="token boolean">null</span><span class="token punctuation">,</span> <span class="token comment">-- id</span></span>
<span class="line">  create_time <span class="token keyword">bigint</span><span class="token punctuation">,</span> <span class="token comment">-- 创建时间</span></span>
<span class="line">  update_time <span class="token keyword">bigint</span><span class="token punctuation">,</span> <span class="token comment">-- 更新时间</span></span>
<span class="line">  delete_time <span class="token keyword">bigint</span><span class="token punctuation">,</span> <span class="token comment">-- 删除时间</span></span>
<span class="line"></span>
<span class="line">  created_at <span class="token keyword">TIMESTAMP</span><span class="token punctuation">,</span> <span class="token comment">-- 创建时间</span></span>
<span class="line">  updated_at <span class="token keyword">TIMESTAMP</span><span class="token punctuation">,</span> <span class="token comment">-- 更新时间</span></span>
<span class="line">  deleted_at <span class="token keyword">TIMESTAMP</span>  <span class="token comment">-- 删除时间</span></span>
<span class="line"><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="年" tabindex="-1"><a class="header-anchor" href="#年"><span>年</span></a></h2>
<div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code><span class="line"><span class="token keyword">select</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> <span class="token keyword">year</span><span class="token punctuation">,</span> <span class="token function">COUNT</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span> <span class="token keyword">as</span> num</span>
<span class="line"><span class="token keyword">from</span> <span class="token string">"user"</span></span>
<span class="line"><span class="token keyword">where</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD'</span><span class="token punctuation">)</span> <span class="token operator">>=</span> <span class="token string">'2023-01-01'</span></span>
<span class="line">  <span class="token operator">and</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD'</span><span class="token punctuation">)</span> <span class="token operator">&lt;=</span> <span class="token string">'2024-01-01'</span></span>
<span class="line"><span class="token keyword">group</span> <span class="token keyword">by</span> <span class="token keyword">year</span></span>
<span class="line"><span class="token keyword">order</span> <span class="token keyword">by</span> <span class="token keyword">year</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">select</span> date_part<span class="token punctuation">(</span><span class="token string">'year'</span><span class="token punctuation">,</span> to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token keyword">as</span> <span class="token keyword">year</span><span class="token punctuation">,</span> <span class="token function">COUNT</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span> <span class="token keyword">as</span> num</span>
<span class="line"><span class="token keyword">from</span> <span class="token string">"user"</span></span>
<span class="line"><span class="token keyword">where</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD'</span><span class="token punctuation">)</span> <span class="token operator">>=</span> <span class="token string">'2023-01-01'</span></span>
<span class="line">  <span class="token operator">and</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD'</span><span class="token punctuation">)</span> <span class="token operator">&lt;=</span> <span class="token string">'2024-01-01'</span></span>
<span class="line"><span class="token keyword">group</span> <span class="token keyword">by</span> <span class="token keyword">year</span></span>
<span class="line"><span class="token keyword">order</span> <span class="token keyword">by</span> <span class="token keyword">year</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code><span class="line"><span class="token keyword">select</span> to_char<span class="token punctuation">(</span>created_at::<span class="token keyword">DATE</span><span class="token punctuation">,</span> <span class="token string">'YYYY'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> <span class="token keyword">year</span><span class="token punctuation">,</span> <span class="token function">COUNT</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span> <span class="token keyword">as</span> num</span>
<span class="line"><span class="token keyword">from</span> <span class="token string">"user"</span></span>
<span class="line"><span class="token keyword">where</span> created_at <span class="token operator">>=</span> <span class="token string">'2023-01-01'</span></span>
<span class="line">  <span class="token operator">and</span> created_at <span class="token operator">&lt;=</span> <span class="token string">'2024-01-01'</span></span>
<span class="line"><span class="token keyword">group</span> <span class="token keyword">by</span> <span class="token keyword">year</span></span>
<span class="line"><span class="token keyword">order</span> <span class="token keyword">by</span> <span class="token keyword">year</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="月" tabindex="-1"><a class="header-anchor" href="#月"><span>月</span></a></h2>
<div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code><span class="line"><span class="token keyword">select</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> <span class="token keyword">month</span><span class="token punctuation">,</span> <span class="token function">COUNT</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span> <span class="token keyword">as</span> num</span>
<span class="line"><span class="token keyword">from</span> <span class="token string">"user"</span></span>
<span class="line"><span class="token keyword">where</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD'</span><span class="token punctuation">)</span> <span class="token operator">>=</span> <span class="token string">'2023-01-01'</span></span>
<span class="line">  <span class="token operator">and</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD'</span><span class="token punctuation">)</span> <span class="token operator">&lt;=</span> <span class="token string">'2024-01-01'</span></span>
<span class="line"><span class="token keyword">group</span> <span class="token keyword">by</span> <span class="token keyword">month</span></span>
<span class="line"><span class="token keyword">order</span> <span class="token keyword">by</span> <span class="token keyword">month</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code><span class="line"><span class="token keyword">select</span> to_char<span class="token punctuation">(</span>created_at::<span class="token keyword">DATE</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> <span class="token keyword">month</span><span class="token punctuation">,</span> <span class="token function">COUNT</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span> <span class="token keyword">as</span> num</span>
<span class="line"><span class="token keyword">from</span> <span class="token string">"user"</span></span>
<span class="line"><span class="token keyword">where</span> created_at <span class="token operator">>=</span> <span class="token string">'2023-01-01'</span></span>
<span class="line">  <span class="token operator">and</span> created_at <span class="token operator">&lt;=</span> <span class="token string">'2024-01-01'</span></span>
<span class="line"><span class="token keyword">group</span> <span class="token keyword">by</span> <span class="token keyword">month</span></span>
<span class="line"><span class="token keyword">order</span> <span class="token keyword">by</span> <span class="token keyword">month</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="周" tabindex="-1"><a class="header-anchor" href="#周"><span>周</span></a></h2>
<div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code><span class="line"><span class="token keyword">select</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span> <span class="token operator">-</span> <span class="token punctuation">(</span>extract<span class="token punctuation">(</span>dow <span class="token keyword">from</span> to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token number">1</span> <span class="token operator">||</span> <span class="token string">'day'</span><span class="token punctuation">)</span>::<span class="token keyword">interval</span><span class="token punctuation">,</span> <span class="token string">'YYYY-mm-dd'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> week<span class="token punctuation">,</span> <span class="token function">COUNT</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span> <span class="token keyword">as</span> num</span>
<span class="line"><span class="token keyword">from</span> <span class="token string">"user"</span></span>
<span class="line"><span class="token keyword">where</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'yyyy-mm-dd'</span><span class="token punctuation">)</span> <span class="token operator">>=</span> <span class="token string">'2023-01-01'</span></span>
<span class="line">  <span class="token operator">and</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'yyyy-mm-dd'</span><span class="token punctuation">)</span> <span class="token operator">&lt;=</span> <span class="token string">'2024-01-01'</span></span>
<span class="line"><span class="token keyword">group</span> <span class="token keyword">by</span> week</span>
<span class="line"><span class="token keyword">order</span> <span class="token keyword">by</span> week<span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code><span class="line"><span class="token keyword">select</span> to_char<span class="token punctuation">(</span>created_at::<span class="token keyword">DATE</span> <span class="token operator">-</span> <span class="token punctuation">(</span>extract<span class="token punctuation">(</span>dow <span class="token keyword">from</span> created_at::<span class="token keyword">TIMESTAMP</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token number">1</span> <span class="token operator">||</span> <span class="token string">'day'</span><span class="token punctuation">)</span>::<span class="token keyword">interval</span><span class="token punctuation">,</span> <span class="token string">'YYYY-mm-dd'</span><span class="token punctuation">)</span> week<span class="token punctuation">,</span> <span class="token function">COUNT</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span> <span class="token keyword">as</span> num</span>
<span class="line"><span class="token keyword">from</span> <span class="token string">"user"</span></span>
<span class="line"><span class="token keyword">where</span> created_at <span class="token operator">>=</span> <span class="token string">'2023-01-01'</span></span>
<span class="line">  <span class="token operator">and</span> created_at <span class="token operator">&lt;=</span> <span class="token string">'2024-01-01'</span></span>
<span class="line"><span class="token keyword">group</span> <span class="token keyword">by</span> week</span>
<span class="line"><span class="token keyword">order</span> <span class="token keyword">by</span> week<span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="日" tabindex="-1"><a class="header-anchor" href="#日"><span>日</span></a></h2>
<div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code><span class="line"><span class="token keyword">select</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> <span class="token keyword">day</span><span class="token punctuation">,</span> <span class="token function">COUNT</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span> <span class="token keyword">as</span> num</span>
<span class="line"><span class="token keyword">from</span> <span class="token string">"user"</span></span>
<span class="line"><span class="token keyword">where</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD'</span><span class="token punctuation">)</span> <span class="token operator">>=</span> <span class="token string">'2023-01-01'</span></span>
<span class="line">  <span class="token operator">and</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD'</span><span class="token punctuation">)</span> <span class="token operator">&lt;=</span> <span class="token string">'2024-01-01'</span></span>
<span class="line"><span class="token keyword">group</span> <span class="token keyword">by</span> <span class="token keyword">day</span></span>
<span class="line"><span class="token keyword">order</span> <span class="token keyword">by</span> <span class="token keyword">day</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code><span class="line"><span class="token keyword">select</span> to_char<span class="token punctuation">(</span>created_at::<span class="token keyword">DATE</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> <span class="token keyword">day</span><span class="token punctuation">,</span> <span class="token function">COUNT</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span> <span class="token keyword">as</span> num</span>
<span class="line"><span class="token keyword">from</span> <span class="token string">"user"</span></span>
<span class="line"><span class="token keyword">where</span> created_at <span class="token operator">>=</span> <span class="token string">'2023-01-01'</span></span>
<span class="line">  <span class="token operator">and</span> created_at <span class="token operator">&lt;=</span> <span class="token string">'2024-01-01'</span></span>
<span class="line"><span class="token keyword">group</span> <span class="token keyword">by</span> <span class="token keyword">day</span></span>
<span class="line"><span class="token keyword">order</span> <span class="token keyword">by</span> <span class="token keyword">day</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="小时" tabindex="-1"><a class="header-anchor" href="#小时"><span>小时</span></a></h2>
<div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code><span class="line"><span class="token keyword">select</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD HH24'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> <span class="token keyword">hour</span><span class="token punctuation">,</span> <span class="token function">COUNT</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span> <span class="token keyword">as</span> num</span>
<span class="line"><span class="token keyword">from</span> <span class="token string">"user"</span></span>
<span class="line"><span class="token keyword">where</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD'</span><span class="token punctuation">)</span> <span class="token operator">>=</span> <span class="token string">'2023-01-01'</span></span>
<span class="line">  <span class="token operator">and</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD'</span><span class="token punctuation">)</span> <span class="token operator">&lt;=</span> <span class="token string">'2024-01-01'</span></span>
<span class="line"><span class="token keyword">group</span> <span class="token keyword">by</span> <span class="token keyword">hour</span></span>
<span class="line"><span class="token keyword">order</span> <span class="token keyword">by</span> <span class="token keyword">hour</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code><span class="line"><span class="token keyword">select</span> to_char<span class="token punctuation">(</span>created_at::<span class="token keyword">DATE</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD HH24'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> <span class="token keyword">hour</span><span class="token punctuation">,</span> <span class="token function">COUNT</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span> <span class="token keyword">as</span> num</span>
<span class="line"><span class="token keyword">from</span> <span class="token string">"user"</span></span>
<span class="line"><span class="token keyword">where</span> created_at <span class="token operator">>=</span> <span class="token string">'2023-01-01'</span></span>
<span class="line">  <span class="token operator">and</span> created_at <span class="token operator">&lt;=</span> <span class="token string">'2024-01-01'</span></span>
<span class="line"><span class="token keyword">group</span> <span class="token keyword">by</span> <span class="token keyword">hour</span></span>
<span class="line"><span class="token keyword">order</span> <span class="token keyword">by</span> <span class="token keyword">hour</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="分钟" tabindex="-1"><a class="header-anchor" href="#分钟"><span>分钟</span></a></h2>
<div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code><span class="line"><span class="token keyword">select</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD HH24:MI'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> <span class="token keyword">minute</span><span class="token punctuation">,</span> <span class="token function">COUNT</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span> <span class="token keyword">as</span> num</span>
<span class="line"><span class="token keyword">from</span> <span class="token string">"user"</span></span>
<span class="line"><span class="token keyword">where</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD'</span><span class="token punctuation">)</span> <span class="token operator">>=</span> <span class="token string">'2023-01-01'</span></span>
<span class="line">  <span class="token operator">and</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD'</span><span class="token punctuation">)</span> <span class="token operator">&lt;=</span> <span class="token string">'2024-01-01'</span></span>
<span class="line"><span class="token keyword">group</span> <span class="token keyword">by</span> <span class="token keyword">minute</span></span>
<span class="line"><span class="token keyword">order</span> <span class="token keyword">by</span> <span class="token keyword">minute</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code><span class="line"><span class="token keyword">select</span> to_char<span class="token punctuation">(</span>created_at::<span class="token keyword">DATE</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD HH24:MI'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> <span class="token keyword">minute</span><span class="token punctuation">,</span> <span class="token function">COUNT</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span> <span class="token keyword">as</span> num</span>
<span class="line"><span class="token keyword">from</span> <span class="token string">"user"</span></span>
<span class="line"><span class="token keyword">where</span> created_at <span class="token operator">>=</span> <span class="token string">'2023-01-01'</span></span>
<span class="line">  <span class="token operator">and</span> created_at <span class="token operator">&lt;=</span> <span class="token string">'2024-01-01'</span></span>
<span class="line"><span class="token keyword">group</span> <span class="token keyword">by</span> <span class="token keyword">minute</span></span>
<span class="line"><span class="token keyword">order</span> <span class="token keyword">by</span> <span class="token keyword">minute</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="秒" tabindex="-1"><a class="header-anchor" href="#秒"><span>秒</span></a></h2>
<div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code><span class="line"><span class="token keyword">select</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD HH24:MI:SS'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> <span class="token keyword">second</span><span class="token punctuation">,</span> <span class="token function">COUNT</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span> <span class="token keyword">as</span> num</span>
<span class="line"><span class="token keyword">from</span> <span class="token string">"user"</span></span>
<span class="line"><span class="token keyword">where</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD'</span><span class="token punctuation">)</span> <span class="token operator">>=</span> <span class="token string">'2023-01-01'</span></span>
<span class="line">  <span class="token operator">and</span> to_char<span class="token punctuation">(</span>to_timestamp<span class="token punctuation">(</span>create_time <span class="token operator">/</span> <span class="token number">1000</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD'</span><span class="token punctuation">)</span> <span class="token operator">&lt;=</span> <span class="token string">'2024-01-01'</span></span>
<span class="line"><span class="token keyword">group</span> <span class="token keyword">by</span> <span class="token keyword">second</span></span>
<span class="line"><span class="token keyword">order</span> <span class="token keyword">by</span> <span class="token keyword">second</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-sql line-numbers-mode" data-highlighter="prismjs" data-ext="sql"><pre v-pre><code><span class="line"><span class="token keyword">select</span> to_char<span class="token punctuation">(</span>created_at::<span class="token keyword">DATE</span><span class="token punctuation">,</span> <span class="token string">'YYYY-MM-DD HH24:MI:SS'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> <span class="token keyword">second</span><span class="token punctuation">,</span> <span class="token function">COUNT</span><span class="token punctuation">(</span><span class="token operator">*</span><span class="token punctuation">)</span> <span class="token keyword">as</span> num</span>
<span class="line"><span class="token keyword">from</span> <span class="token string">"user"</span></span>
<span class="line"><span class="token keyword">where</span> created_at <span class="token operator">>=</span> <span class="token string">'2023-01-01'</span></span>
<span class="line">  <span class="token operator">and</span> created_at <span class="token operator">&lt;=</span> <span class="token string">'2024-01-01'</span></span>
<span class="line"><span class="token keyword">group</span> <span class="token keyword">by</span> <span class="token keyword">second</span></span>
<span class="line"><span class="token keyword">order</span> <span class="token keyword">by</span> <span class="token keyword">second</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="参考资料" tabindex="-1"><a class="header-anchor" href="#参考资料"><span>参考资料</span></a></h2>
<ul>
<li><a href="https://www.cnblogs.com/chenyablog/p/12482855.html" target="_blank" rel="noopener noreferrer">PostgreSQL 实现按年、月、日、周、时、分、秒分组统计</a></li>
</ul>
</div></template>


