<template><div><h1 id="解决selenium的报错-stale-element-reference-element-is-not-attached-to-the-page-document" tabindex="-1"><a class="header-anchor" href="#解决selenium的报错-stale-element-reference-element-is-not-attached-to-the-page-document"><span>解决Selenium的报错：stale element reference: element is not attached to the page document</span></a></h1>
<p>第一次使用Selenium后，在循环处理时，我遇到了一个莫名其妙的错误，我被卡住了一阵子，故而我留下本文作为备忘录。</p>
<div class="language-text line-numbers-mode" data-highlighter="prismjs" data-ext="text"><pre v-pre><code><span class="line">stale element reference: element is not attached to the page document</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="有问题的代码" tabindex="-1"><a class="header-anchor" href="#有问题的代码"><span>有问题的代码</span></a></h2>
<p>请原谅凌乱的代码。。</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py"><pre v-pre><code><span class="line">divEl <span class="token operator">=</span> driver<span class="token punctuation">.</span>find_element_by_class_name<span class="token punctuation">(</span><span class="token string">"htBlock-adjastableTableF_inner"</span><span class="token punctuation">)</span></span>
<span class="line">tableElem <span class="token operator">=</span> divEl<span class="token punctuation">.</span>find_elements<span class="token punctuation">(</span>By<span class="token punctuation">.</span>TAG_NAME<span class="token punctuation">,</span> <span class="token string">"table"</span><span class="token punctuation">)</span></span>
<span class="line">tbodys <span class="token operator">=</span> tableElem<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span>find_elements<span class="token punctuation">(</span>By<span class="token punctuation">.</span>TAG_NAME<span class="token punctuation">,</span> <span class="token string">"tbody"</span><span class="token punctuation">)</span></span>
<span class="line">trs <span class="token operator">=</span> tbodys<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span>find_elements<span class="token punctuation">(</span>By<span class="token punctuation">.</span>TAG_NAME<span class="token punctuation">,</span> <span class="token string">"tr"</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token builtin">len</span><span class="token punctuation">(</span>trs<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">:</span></span>
<span class="line">    tmp1 <span class="token operator">=</span> trs<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span>find_element_by_class_name<span class="token punctuation">(</span><span class="token string">"htBlock-adjastableTableF_actionRow"</span><span class="token punctuation">)</span>  <span class="token comment"># td</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>本次循环中，第0次循环没有问题</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py"><pre v-pre><code><span class="line">tmp1 <span class="token operator">=</span> trs<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span>find_element_by_class_name<span class="token punctuation">(</span><span class="token string">"htBlock-adjastableTableF_actionRow"</span><span class="token punctuation">)</span>  <span class="token comment"># td</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>可以完成，但在第一个循环中出现标题错误。</p>
<h2 id="解决方案" tabindex="-1"><a class="header-anchor" href="#解决方案"><span>解决方案</span></a></h2>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py"><pre v-pre><code><span class="line">divEl <span class="token operator">=</span> driver<span class="token punctuation">.</span>find_element_by_class_name<span class="token punctuation">(</span><span class="token string">"htBlock-adjastableTableF_inner"</span><span class="token punctuation">)</span></span>
<span class="line">tableElem <span class="token operator">=</span> divEl<span class="token punctuation">.</span>find_elements<span class="token punctuation">(</span>By<span class="token punctuation">.</span>TAG_NAME<span class="token punctuation">,</span> <span class="token string">"table"</span><span class="token punctuation">)</span></span>
<span class="line">tbodys <span class="token operator">=</span> tableElem<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span>find_elements<span class="token punctuation">(</span>By<span class="token punctuation">.</span>TAG_NAME<span class="token punctuation">,</span> <span class="token string">"tbody"</span><span class="token punctuation">)</span></span>
<span class="line">trs <span class="token operator">=</span> tbodys<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span>find_elements<span class="token punctuation">(</span>By<span class="token punctuation">.</span>TAG_NAME<span class="token punctuation">,</span> <span class="token string">"tr"</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token builtin">len</span><span class="token punctuation">(</span>trs<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">:</span></span>
<span class="line">    divEl <span class="token operator">=</span> driver<span class="token punctuation">.</span>find_element_by_class_name<span class="token punctuation">(</span><span class="token string">"htBlock-adjastableTableF_inner"</span><span class="token punctuation">)</span></span>
<span class="line">    tableElem <span class="token operator">=</span> divEl<span class="token punctuation">.</span>find_elements<span class="token punctuation">(</span>By<span class="token punctuation">.</span>TAG_NAME<span class="token punctuation">,</span> <span class="token string">"table"</span><span class="token punctuation">)</span></span>
<span class="line">    tbodys <span class="token operator">=</span> tableElem<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span>find_elements<span class="token punctuation">(</span>By<span class="token punctuation">.</span>TAG_NAME<span class="token punctuation">,</span> <span class="token string">"tbody"</span><span class="token punctuation">)</span></span>
<span class="line">    trs <span class="token operator">=</span> tbodys<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span>find_elements<span class="token punctuation">(</span>By<span class="token punctuation">.</span>TAG_NAME<span class="token punctuation">,</span> <span class="token string">"tr"</span><span class="token punctuation">)</span></span>
<span class="line">    tmp1 <span class="token operator">=</span> trs<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span>find_element_by_class_name<span class="token punctuation">(</span><span class="token string">"htBlock-adjastableTableF_actionRow"</span><span class="token punctuation">)</span>  <span class="token comment"># td</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>当我在循环中实时获取页面中的DOM信息时，程序运行没有问题。</p>
<p>以上。</p>
<p>简单来说，在for循环里面，必须要现查现用，否则就会得到陈旧的页面的信息，就会报错。</p>
<h2 id="原文地址" tabindex="-1"><a class="header-anchor" href="#原文地址"><span>原文地址</span></a></h2>
<ul>
<li><a href="https://qiita.com/kenmaro/items/09549799285d76ce63fb" target="_blank" rel="noopener noreferrer">Selenium でループを書いたときの　stale element reference: element is not attached to the page document　エラー回避備忘録</a></li>
</ul>
</div></template>


