<template><div><h1 id="thingsboard设备登陆认证" tabindex="-1"><a class="header-anchor" href="#thingsboard设备登陆认证"><span>ThingsBoard设备登陆认证</span></a></h1>
<h2 id="thingsboard设备有关的表" tabindex="-1"><a class="header-anchor" href="#thingsboard设备有关的表"><span>ThingsBoard设备有关的表</span></a></h2>
<p><img src="/assets/images/thingsboard/thingsboard_device_table.png" alt="thingsboard_device_table"></p>
<ul>
<li><strong>device_profile</strong> 这个表相当于国内的“产品”的概念</li>
<li><strong>ota_package</strong> 这个表是OTA升级包相关的数据</li>
<li><strong>device</strong> 这个表是设备的数据</li>
<li><strong>device_credentials</strong> 这个表是设备的登陆验证凭证信息</li>
</ul>
<h2 id="支持的凭证类型" tabindex="-1"><a class="header-anchor" href="#支持的凭证类型"><span>支持的凭证类型</span></a></h2>
<ul>
<li>访问令牌</li>
<li>MQTT验证信息</li>
<li>x509证书</li>
<li>LWM2M</li>
</ul>
<h2 id="前端定义的相关类" tabindex="-1"><a class="header-anchor" href="#前端定义的相关类"><span>前端定义的相关类</span></a></h2>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">export</span> <span class="token keyword">enum</span> DeviceCredentialsType <span class="token punctuation">{</span></span>
<span class="line">  <span class="token constant">ACCESS_TOKEN</span> <span class="token operator">=</span> <span class="token string">'ACCESS_TOKEN'</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token constant">X509_CERTIFICATE</span> <span class="token operator">=</span> <span class="token string">'X509_CERTIFICATE'</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token constant">MQTT_BASIC</span> <span class="token operator">=</span> <span class="token string">'MQTT_BASIC'</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token constant">LWM2M_CREDENTIALS</span> <span class="token operator">=</span> <span class="token string">'LWM2M_CREDENTIALS'</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">DeviceCredentialsId</span> <span class="token keyword">implements</span> <span class="token class-name">HasUUID</span> <span class="token punctuation">{</span></span>
<span class="line">  id<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">constructor</span><span class="token punctuation">(</span>id<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">this</span><span class="token punctuation">.</span>id <span class="token operator">=</span> id<span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">export</span> <span class="token keyword">interface</span> <span class="token class-name">DeviceCredentials</span> <span class="token keyword">extends</span> <span class="token class-name">BaseData<span class="token operator">&lt;</span>DeviceCredentialsId<span class="token operator">></span></span> <span class="token punctuation">{</span></span>
<span class="line">  deviceId<span class="token operator">:</span> DeviceId<span class="token punctuation">;</span></span>
<span class="line">  credentialsType<span class="token operator">:</span> DeviceCredentialsType<span class="token punctuation">;</span></span>
<span class="line">  credentialsId<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">;</span></span>
<span class="line">  credentialsValue<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">export</span> <span class="token keyword">interface</span> <span class="token class-name">DeviceCredentialMQTTBasic</span> <span class="token punctuation">{</span></span>
<span class="line">  clientId<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">;</span></span>
<span class="line">  userName<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">;</span></span>
<span class="line">  password<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="后端定义的相关类" tabindex="-1"><a class="header-anchor" href="#后端定义的相关类"><span>后端定义的相关类</span></a></h2>
<div class="language-java line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre v-pre><code><span class="line"><span class="token annotation punctuation">@ApiModel</span></span>
<span class="line"><span class="token annotation punctuation">@EqualsAndHashCode</span><span class="token punctuation">(</span>callSuper <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">public</span> <span class="token keyword">class</span> <span class="token class-name">DeviceCredentials</span> <span class="token keyword">extends</span> <span class="token class-name">BaseData</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">DeviceCredentialsId</span><span class="token punctuation">></span></span> <span class="token keyword">implements</span> <span class="token class-name">DeviceCredentialsFilter</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">private</span> <span class="token keyword">static</span> <span class="token keyword">final</span> <span class="token keyword">long</span> serialVersionUID <span class="token operator">=</span> <span class="token operator">-</span><span class="token number">7869261127032877765L</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">private</span> <span class="token class-name">DeviceId</span> deviceId<span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">private</span> <span class="token class-name">DeviceCredentialsType</span> credentialsType<span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">private</span> <span class="token class-name">String</span> credentialsId<span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">private</span> <span class="token class-name">String</span> credentialsValue<span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token annotation punctuation">@Data</span></span>
<span class="line"><span class="token keyword">public</span> <span class="token keyword">class</span> <span class="token class-name">ProvisionDeviceCredentialsData</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">private</span> <span class="token keyword">final</span> <span class="token class-name">String</span> token<span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">private</span> <span class="token keyword">final</span> <span class="token class-name">String</span> clientId<span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">private</span> <span class="token keyword">final</span> <span class="token class-name">String</span> username<span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">private</span> <span class="token keyword">final</span> <span class="token class-name">String</span> password<span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">private</span> <span class="token keyword">final</span> <span class="token class-name">String</span> x509CertHash<span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token annotation punctuation">@Data</span></span>
<span class="line"><span class="token keyword">public</span> <span class="token keyword">class</span> <span class="token class-name">BasicMqttCredentials</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">private</span> <span class="token class-name">String</span> clientId<span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">private</span> <span class="token class-name">String</span> userName<span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">private</span> <span class="token class-name">String</span> password<span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="各类型凭证如何存数据" tabindex="-1"><a class="header-anchor" href="#各类型凭证如何存数据"><span>各类型凭证如何存数据</span></a></h2>
<p>处理数据的代码在：<code v-pre>DeviceCredentialsServiceImpl</code>和<code v-pre>DeviceServiceImpl</code>中</p>
<h3 id="访问令牌" tabindex="-1"><a class="header-anchor" href="#访问令牌"><span>访问令牌</span></a></h3>
<table>
<thead>
<tr>
<th>字段</th>
<th>数值</th>
</tr>
</thead>
<tbody>
<tr>
<td>credentials_type</td>
<td>ACCESS_TOKEN</td>
</tr>
<tr>
<td>credentials_id</td>
<td>访问令牌</td>
</tr>
<tr>
<td>credentials_value</td>
<td>无</td>
</tr>
</tbody>
</table>
<h3 id="mqtt验证信息" tabindex="-1"><a class="header-anchor" href="#mqtt验证信息"><span>MQTT验证信息</span></a></h3>
<table>
<thead>
<tr>
<th>字段</th>
<th>数值</th>
</tr>
</thead>
<tbody>
<tr>
<td>credentials_type</td>
<td>MQTT_BASIC</td>
</tr>
<tr>
<td>credentials_id</td>
<td><li>clientId为空：userName</li><li>userName为空：SHA3(clientId)</li><li>其他情况：SHA3(clientId | userName)</li></td>
</tr>
<tr>
<td>credentials_value</td>
<td>{ userName:&quot;&quot;, password:&quot;&quot;, clientId:&quot;&quot; }</td>
</tr>
</tbody>
</table>
<h3 id="x509证书" tabindex="-1"><a class="header-anchor" href="#x509证书"><span>x509证书</span></a></h3>
<table>
<thead>
<tr>
<th>字段</th>
<th>数值</th>
</tr>
</thead>
<tbody>
<tr>
<td>credentials_type</td>
<td>X509_CERTIFICATE</td>
</tr>
<tr>
<td>credentials_id</td>
<td>SHA3(掐头去尾去换行符的证书)</td>
</tr>
<tr>
<td>credentials_value</td>
<td>掐头去尾去换行符的证书</td>
</tr>
</tbody>
</table>
<h2 id="如何登陆认证设备" tabindex="-1"><a class="header-anchor" href="#如何登陆认证设备"><span>如何登陆认证设备</span></a></h2>
<p><img src="/assets/images/thingsboard/thingsboard_mqtt_process_message.drawio.svg" alt="处理MQTT消息流程"></p>
<p>具体处理连接的代码在：<code v-pre>MqttTransportHandler</code>中。</p>
<p>从代码中可以知道，当用户名或者客户端ID为<code v-pre>PROVISION</code>时，设备会被认为是设备的初始化，需要进行设备的初始化，否则会被认为是设备的登陆，需要进行设备的登陆。</p>
<div class="language-java line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre v-pre><code><span class="line"><span class="token keyword">void</span> <span class="token function">processConnect</span><span class="token punctuation">(</span><span class="token class-name">ChannelHandlerContext</span> ctx<span class="token punctuation">,</span> <span class="token class-name">MqttConnectMessage</span> msg<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    log<span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span><span class="token string">"[{}] Processing connect msg for client: {}!"</span><span class="token punctuation">,</span> sessionId<span class="token punctuation">,</span> msg<span class="token punctuation">.</span><span class="token function">payload</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">clientIdentifier</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token class-name">String</span> userName <span class="token operator">=</span> msg<span class="token punctuation">.</span><span class="token function">payload</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">userName</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token class-name">String</span> clientId <span class="token operator">=</span> msg<span class="token punctuation">.</span><span class="token function">payload</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">clientIdentifier</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token class-name">DataConstants</span><span class="token punctuation">.</span><span class="token constant">PROVISION</span><span class="token punctuation">.</span><span class="token function">equals</span><span class="token punctuation">(</span>userName<span class="token punctuation">)</span> <span class="token operator">||</span> <span class="token class-name">DataConstants</span><span class="token punctuation">.</span><span class="token constant">PROVISION</span><span class="token punctuation">.</span><span class="token function">equals</span><span class="token punctuation">(</span>clientId<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">        deviceSessionCtx<span class="token punctuation">.</span><span class="token function">setProvisionOnly</span><span class="token punctuation">(</span><span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        ctx<span class="token punctuation">.</span><span class="token function">writeAndFlush</span><span class="token punctuation">(</span><span class="token function">createMqttConnAckMsg</span><span class="token punctuation">(</span><span class="token constant">CONNECTION_ACCEPTED</span><span class="token punctuation">,</span> msg<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token class-name">X509Certificate</span> cert<span class="token punctuation">;</span></span>
<span class="line">        <span class="token keyword">if</span> <span class="token punctuation">(</span>sslHandler <span class="token operator">!=</span> <span class="token keyword">null</span> <span class="token operator">&amp;&amp;</span> <span class="token punctuation">(</span>cert <span class="token operator">=</span> <span class="token function">getX509Certificate</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token function">processX509CertConnect</span><span class="token punctuation">(</span>ctx<span class="token punctuation">,</span> cert<span class="token punctuation">,</span> msg<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token function">processAuthTokenConnect</span><span class="token punctuation">(</span>ctx<span class="token punctuation">,</span> msg<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>MqttTransportHandler::processAuthTokenConnect</code>方法是连同访问令牌和MQTT验证一起做的。</p>
<div class="language-java line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre v-pre><code><span class="line"><span class="token keyword">private</span> <span class="token keyword">void</span> <span class="token function">processAuthTokenConnect</span><span class="token punctuation">(</span><span class="token class-name">ChannelHandlerContext</span> ctx<span class="token punctuation">,</span> <span class="token class-name">MqttConnectMessage</span> connectMessage<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token class-name">String</span> userName <span class="token operator">=</span> connectMessage<span class="token punctuation">.</span><span class="token function">payload</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">userName</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    log<span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span><span class="token string">"[{}][{}] Processing connect msg for client with user name: {}!"</span><span class="token punctuation">,</span> address<span class="token punctuation">,</span> sessionId<span class="token punctuation">,</span> userName<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token class-name">TransportProtos<span class="token punctuation">.</span>ValidateBasicMqttCredRequestMsg<span class="token punctuation">.</span>Builder</span> request <span class="token operator">=</span> <span class="token class-name">TransportProtos<span class="token punctuation">.</span>ValidateBasicMqttCredRequestMsg</span><span class="token punctuation">.</span><span class="token function">newBuilder</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">            <span class="token punctuation">.</span><span class="token function">setClientId</span><span class="token punctuation">(</span>connectMessage<span class="token punctuation">.</span><span class="token function">payload</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">clientIdentifier</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">if</span> <span class="token punctuation">(</span>userName <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">        request<span class="token punctuation">.</span><span class="token function">setUserName</span><span class="token punctuation">(</span>userName<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    <span class="token keyword">byte</span><span class="token punctuation">[</span><span class="token punctuation">]</span> passwordBytes <span class="token operator">=</span> connectMessage<span class="token punctuation">.</span><span class="token function">payload</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">passwordInBytes</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">if</span> <span class="token punctuation">(</span>passwordBytes <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token class-name">String</span> password <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">String</span><span class="token punctuation">(</span>passwordBytes<span class="token punctuation">,</span> <span class="token class-name">CharsetUtil</span><span class="token punctuation">.</span><span class="token constant">UTF_8</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        request<span class="token punctuation">.</span><span class="token function">setPassword</span><span class="token punctuation">(</span>password<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    transportService<span class="token punctuation">.</span><span class="token function">process</span><span class="token punctuation">(</span><span class="token class-name">DeviceTransportType</span><span class="token punctuation">.</span><span class="token constant">MQTT</span><span class="token punctuation">,</span> request<span class="token punctuation">.</span><span class="token function">build</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token keyword">new</span> <span class="token class-name">TransportServiceCallback</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                <span class="token annotation punctuation">@Override</span></span>
<span class="line">                <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">onSuccess</span><span class="token punctuation">(</span><span class="token class-name">ValidateDeviceCredentialsResponse</span> msg<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                    <span class="token function">onValidateDeviceResponse</span><span class="token punctuation">(</span>msg<span class="token punctuation">,</span> ctx<span class="token punctuation">,</span> connectMessage<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">                <span class="token annotation punctuation">@Override</span></span>
<span class="line">                <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">onError</span><span class="token punctuation">(</span><span class="token class-name">Throwable</span> e<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                    log<span class="token punctuation">.</span><span class="token function">trace</span><span class="token punctuation">(</span><span class="token string">"[{}] Failed to process credentials: {}"</span><span class="token punctuation">,</span> address<span class="token punctuation">,</span> userName<span class="token punctuation">,</span> e<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                    ctx<span class="token punctuation">.</span><span class="token function">writeAndFlush</span><span class="token punctuation">(</span><span class="token function">createMqttConnAckMsg</span><span class="token punctuation">(</span><span class="token class-name">MqttConnectReturnCode</span><span class="token punctuation">.</span><span class="token constant">CONNECTION_REFUSED_SERVER_UNAVAILABLE</span><span class="token punctuation">,</span> connectMessage<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                    ctx<span class="token punctuation">.</span><span class="token function">close</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                <span class="token punctuation">}</span></span>
<span class="line">            <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上一步的<code v-pre>transportService.process</code>传递到了<code v-pre>DefaultTransportService::process</code>当中做了处理。</p>
<div class="language-java line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre v-pre><code><span class="line"><span class="token annotation punctuation">@Override</span></span>
<span class="line"><span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">process</span><span class="token punctuation">(</span><span class="token class-name">DeviceTransportType</span> transportType<span class="token punctuation">,</span> <span class="token class-name">TransportProtos<span class="token punctuation">.</span>ValidateDeviceTokenRequestMsg</span> msg<span class="token punctuation">,</span></span>
<span class="line">                    <span class="token class-name">TransportServiceCallback</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">ValidateDeviceCredentialsResponse</span><span class="token punctuation">></span></span> callback<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    log<span class="token punctuation">.</span><span class="token function">trace</span><span class="token punctuation">(</span><span class="token string">"Processing msg: {}"</span><span class="token punctuation">,</span> msg<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token class-name">TbProtoQueueMsg</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">TransportApiRequestMsg</span><span class="token punctuation">></span></span> protoMsg <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">TbProtoQueueMsg</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token constant">UUID</span><span class="token punctuation">.</span><span class="token function">randomUUID</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token class-name">TransportApiRequestMsg</span><span class="token punctuation">.</span><span class="token function">newBuilder</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">setValidateTokenRequestMsg</span><span class="token punctuation">(</span>msg<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">build</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token function">doProcess</span><span class="token punctuation">(</span>transportType<span class="token punctuation">,</span> protoMsg<span class="token punctuation">,</span> callback<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>请求的消息被翻译成了内部队列的Protobuf的消息，然后再继续投递到<code v-pre>DefaultTransportService::doProcess</code>中。</p>
<div class="language-java line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre v-pre><code><span class="line"><span class="token keyword">private</span> <span class="token keyword">void</span> <span class="token function">doProcess</span><span class="token punctuation">(</span><span class="token class-name">DeviceTransportType</span> transportType<span class="token punctuation">,</span> <span class="token class-name">TbProtoQueueMsg</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">TransportApiRequestMsg</span><span class="token punctuation">></span></span> protoMsg<span class="token punctuation">,</span></span>
<span class="line">                       <span class="token class-name">TransportServiceCallback</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">ValidateDeviceCredentialsResponse</span><span class="token punctuation">></span></span> callback<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token class-name">ListenableFuture</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">ValidateDeviceCredentialsResponse</span><span class="token punctuation">></span></span> response <span class="token operator">=</span> <span class="token class-name">Futures</span><span class="token punctuation">.</span><span class="token function">transform</span><span class="token punctuation">(</span>transportApiRequestTemplate<span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span>protoMsg<span class="token punctuation">)</span><span class="token punctuation">,</span> tmp <span class="token operator">-></span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token class-name">TransportProtos<span class="token punctuation">.</span>ValidateDeviceCredentialsResponseMsg</span> msg <span class="token operator">=</span> tmp<span class="token punctuation">.</span><span class="token function">getValue</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">getValidateCredResponseMsg</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token class-name">ValidateDeviceCredentialsResponse<span class="token punctuation">.</span>ValidateDeviceCredentialsResponseBuilder</span> result <span class="token operator">=</span> <span class="token class-name">ValidateDeviceCredentialsResponse</span><span class="token punctuation">.</span><span class="token function">builder</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token keyword">if</span> <span class="token punctuation">(</span>msg<span class="token punctuation">.</span><span class="token function">hasDeviceInfo</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">            result<span class="token punctuation">.</span><span class="token function">credentials</span><span class="token punctuation">(</span>msg<span class="token punctuation">.</span><span class="token function">getCredentialsBody</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token class-name">TransportDeviceInfo</span> tdi <span class="token operator">=</span> <span class="token function">getTransportDeviceInfo</span><span class="token punctuation">(</span>msg<span class="token punctuation">.</span><span class="token function">getDeviceInfo</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">            result<span class="token punctuation">.</span><span class="token function">deviceInfo</span><span class="token punctuation">(</span>tdi<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token class-name">ByteString</span> profileBody <span class="token operator">=</span> msg<span class="token punctuation">.</span><span class="token function">getProfileBody</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>profileBody<span class="token punctuation">.</span><span class="token function">isEmpty</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                <span class="token class-name">DeviceProfile</span> profile <span class="token operator">=</span> deviceProfileCache<span class="token punctuation">.</span><span class="token function">getOrCreate</span><span class="token punctuation">(</span>tdi<span class="token punctuation">.</span><span class="token function">getDeviceProfileId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> profileBody<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                <span class="token keyword">if</span> <span class="token punctuation">(</span>transportType <span class="token operator">!=</span> <span class="token class-name">DeviceTransportType</span><span class="token punctuation">.</span><span class="token constant">DEFAULT</span></span>
<span class="line">                        <span class="token operator">&amp;&amp;</span> profile <span class="token operator">!=</span> <span class="token keyword">null</span> <span class="token operator">&amp;&amp;</span> profile<span class="token punctuation">.</span><span class="token function">getTransportType</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">!=</span> <span class="token class-name">DeviceTransportType</span><span class="token punctuation">.</span><span class="token constant">DEFAULT</span> <span class="token operator">&amp;&amp;</span> profile<span class="token punctuation">.</span><span class="token function">getTransportType</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">!=</span> transportType<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                    log<span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span><span class="token string">"[{}] Device profile [{}] has different transport type: {}, expected: {}"</span><span class="token punctuation">,</span> tdi<span class="token punctuation">.</span><span class="token function">getDeviceId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> tdi<span class="token punctuation">.</span><span class="token function">getDeviceProfileId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> profile<span class="token punctuation">.</span><span class="token function">getTransportType</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> transportType<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                    <span class="token keyword">throw</span> <span class="token keyword">new</span> <span class="token class-name">IllegalStateException</span><span class="token punctuation">(</span><span class="token string">"Device profile has different transport type: "</span> <span class="token operator">+</span> profile<span class="token punctuation">.</span><span class="token function">getTransportType</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">". Expected: "</span> <span class="token operator">+</span> transportType<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                <span class="token punctuation">}</span></span>
<span class="line">                result<span class="token punctuation">.</span><span class="token function">deviceProfile</span><span class="token punctuation">(</span>profile<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token punctuation">}</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">        <span class="token keyword">return</span> result<span class="token punctuation">.</span><span class="token function">build</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token class-name">MoreExecutors</span><span class="token punctuation">.</span><span class="token function">directExecutor</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token class-name">AsyncCallbackTemplate</span><span class="token punctuation">.</span><span class="token function">withCallback</span><span class="token punctuation">(</span>response<span class="token punctuation">,</span> callback<span class="token operator">::</span><span class="token function">onSuccess</span><span class="token punctuation">,</span> callback<span class="token operator">::</span><span class="token function">onError</span><span class="token punctuation">,</span> transportCallbackExecutor<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>DefaultTransportService::doProcess</code>中把通过<code v-pre>DeviceCredentials</code>查询<code v-pre>DeviceProfile</code>信息，并且把结果返回给<code v-pre>TransportServiceCallback</code>。</p>
<div class="language-java line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre v-pre><code><span class="line">onValidateDeviceResponse</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>此时回调回到了<code v-pre>MqttTransportHandler::processAuthTokenConnect</code>，进入到<code v-pre>MqttTransportHandler::onValidateDeviceResponse</code>处理。</p>
<div class="language-java line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre v-pre><code><span class="line"><span class="token keyword">private</span> <span class="token keyword">void</span> <span class="token function">onValidateDeviceResponse</span><span class="token punctuation">(</span><span class="token class-name">ValidateDeviceCredentialsResponse</span> msg<span class="token punctuation">,</span> <span class="token class-name">ChannelHandlerContext</span> ctx<span class="token punctuation">,</span> <span class="token class-name">MqttConnectMessage</span> connectMessage<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>msg<span class="token punctuation">.</span><span class="token function">hasDeviceInfo</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">        context<span class="token punctuation">.</span><span class="token function">onAuthFailure</span><span class="token punctuation">(</span>address<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        ctx<span class="token punctuation">.</span><span class="token function">writeAndFlush</span><span class="token punctuation">(</span><span class="token function">createMqttConnAckMsg</span><span class="token punctuation">(</span><span class="token constant">CONNECTION_REFUSED_NOT_AUTHORIZED</span><span class="token punctuation">,</span> connectMessage<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        ctx<span class="token punctuation">.</span><span class="token function">close</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span></span>
<span class="line">        context<span class="token punctuation">.</span><span class="token function">onAuthSuccess</span><span class="token punctuation">(</span>address<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        deviceSessionCtx<span class="token punctuation">.</span><span class="token function">setDeviceInfo</span><span class="token punctuation">(</span>msg<span class="token punctuation">.</span><span class="token function">getDeviceInfo</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        deviceSessionCtx<span class="token punctuation">.</span><span class="token function">setDeviceProfile</span><span class="token punctuation">(</span>msg<span class="token punctuation">.</span><span class="token function">getDeviceProfile</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        deviceSessionCtx<span class="token punctuation">.</span><span class="token function">setSessionInfo</span><span class="token punctuation">(</span><span class="token class-name">SessionInfoCreator</span><span class="token punctuation">.</span><span class="token function">create</span><span class="token punctuation">(</span>msg<span class="token punctuation">,</span> context<span class="token punctuation">,</span> sessionId<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        transportService<span class="token punctuation">.</span><span class="token function">process</span><span class="token punctuation">(</span>deviceSessionCtx<span class="token punctuation">.</span><span class="token function">getSessionInfo</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token class-name">DefaultTransportService</span><span class="token punctuation">.</span><span class="token function">getSessionEventMsg</span><span class="token punctuation">(</span><span class="token class-name">SessionEvent</span><span class="token punctuation">.</span><span class="token constant">OPEN</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token keyword">new</span> <span class="token class-name">TransportServiceCallback</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">Void</span><span class="token punctuation">></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token annotation punctuation">@Override</span></span>
<span class="line">            <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">onSuccess</span><span class="token punctuation">(</span><span class="token class-name">Void</span> msg<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                <span class="token class-name">SessionMetaData</span> sessionMetaData <span class="token operator">=</span> transportService<span class="token punctuation">.</span><span class="token function">registerAsyncSession</span><span class="token punctuation">(</span>deviceSessionCtx<span class="token punctuation">.</span><span class="token function">getSessionInfo</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token class-name">MqttTransportHandler</span><span class="token punctuation">.</span><span class="token keyword">this</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                <span class="token function">checkGatewaySession</span><span class="token punctuation">(</span>sessionMetaData<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                ctx<span class="token punctuation">.</span><span class="token function">writeAndFlush</span><span class="token punctuation">(</span><span class="token function">createMqttConnAckMsg</span><span class="token punctuation">(</span><span class="token constant">CONNECTION_ACCEPTED</span><span class="token punctuation">,</span> connectMessage<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                deviceSessionCtx<span class="token punctuation">.</span><span class="token function">setConnected</span><span class="token punctuation">(</span><span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                log<span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span><span class="token string">"[{}] Client connected!"</span><span class="token punctuation">,</span> sessionId<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                transportService<span class="token punctuation">.</span><span class="token function">getCallbackExecutor</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">execute</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-></span> <span class="token function">processMsgQueue</span><span class="token punctuation">(</span>ctx<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//this callback will execute in Producer worker thread and hard or blocking work have to be submitted to the separate thread.</span></span>
<span class="line">            <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">            <span class="token annotation punctuation">@Override</span></span>
<span class="line">            <span class="token keyword">public</span> <span class="token keyword">void</span> <span class="token function">onError</span><span class="token punctuation">(</span><span class="token class-name">Throwable</span> e<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                <span class="token keyword">if</span> <span class="token punctuation">(</span>e <span class="token keyword">instanceof</span> <span class="token class-name">TbRateLimitsException</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                    log<span class="token punctuation">.</span><span class="token function">trace</span><span class="token punctuation">(</span><span class="token string">"[{}] Failed to submit session event: {}"</span><span class="token punctuation">,</span> sessionId<span class="token punctuation">,</span> e<span class="token punctuation">.</span><span class="token function">getMessage</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span></span>
<span class="line">                    log<span class="token punctuation">.</span><span class="token function">warn</span><span class="token punctuation">(</span><span class="token string">"[{}] Failed to submit session event"</span><span class="token punctuation">,</span> sessionId<span class="token punctuation">,</span> e<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                <span class="token punctuation">}</span></span>
<span class="line">                ctx<span class="token punctuation">.</span><span class="token function">writeAndFlush</span><span class="token punctuation">(</span><span class="token function">createMqttConnAckMsg</span><span class="token punctuation">(</span><span class="token class-name">MqttConnectReturnCode</span><span class="token punctuation">.</span><span class="token constant">CONNECTION_REFUSED_SERVER_UNAVAILABLE</span><span class="token punctuation">,</span> connectMessage<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                ctx<span class="token punctuation">.</span><span class="token function">close</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token punctuation">}</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>context.onAuthSuccess</code>主要做了限流。</p>
<p>接着最终应该送给了<code v-pre>DeviceActorMessageProcessor::processSessionStateMsgs</code>。</p>
<div class="language-java line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre v-pre><code><span class="line"><span class="token keyword">private</span> <span class="token keyword">void</span> <span class="token function">processSessionStateMsgs</span><span class="token punctuation">(</span><span class="token class-name">SessionInfoProto</span> sessionInfo<span class="token punctuation">,</span> <span class="token class-name">SessionEventMsg</span> msg<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token class-name">UUID</span> sessionId <span class="token operator">=</span> <span class="token function">getSessionId</span><span class="token punctuation">(</span>sessionInfo<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token class-name">Objects</span><span class="token punctuation">.</span><span class="token function">requireNonNull</span><span class="token punctuation">(</span>sessionId<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">if</span> <span class="token punctuation">(</span>msg<span class="token punctuation">.</span><span class="token function">getEvent</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">==</span> <span class="token class-name">SessionEvent</span><span class="token punctuation">.</span><span class="token constant">OPEN</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token keyword">if</span> <span class="token punctuation">(</span>sessions<span class="token punctuation">.</span><span class="token function">containsKey</span><span class="token punctuation">(</span>sessionId<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">            log<span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span><span class="token string">"[{}] Received duplicate session open event [{}]"</span><span class="token punctuation">,</span> deviceId<span class="token punctuation">,</span> sessionId<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token keyword">return</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">        log<span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span><span class="token string">"[{}] Processing new session [{}]. Current sessions size {}"</span><span class="token punctuation">,</span> deviceId<span class="token punctuation">,</span> sessionId<span class="token punctuation">,</span> sessions<span class="token punctuation">.</span><span class="token function">size</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        sessions<span class="token punctuation">.</span><span class="token function">put</span><span class="token punctuation">(</span>sessionId<span class="token punctuation">,</span> <span class="token keyword">new</span> <span class="token class-name">SessionInfoMetaData</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">SessionInfo</span><span class="token punctuation">(</span><span class="token class-name">SessionType</span><span class="token punctuation">.</span><span class="token constant">ASYNC</span><span class="token punctuation">,</span> sessionInfo<span class="token punctuation">.</span><span class="token function">getNodeId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token keyword">if</span> <span class="token punctuation">(</span>sessions<span class="token punctuation">.</span><span class="token function">size</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">==</span> <span class="token number">1</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token function">reportSessionOpen</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">        systemContext<span class="token punctuation">.</span><span class="token function">getDeviceStateService</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">onDeviceActivity</span><span class="token punctuation">(</span>tenantId<span class="token punctuation">,</span> deviceId<span class="token punctuation">,</span> <span class="token class-name">System</span><span class="token punctuation">.</span><span class="token function">currentTimeMillis</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token function">dumpSessions</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span>msg<span class="token punctuation">.</span><span class="token function">getEvent</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">==</span> <span class="token class-name">SessionEvent</span><span class="token punctuation">.</span><span class="token constant">CLOSED</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">        log<span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span><span class="token string">"[{}] Canceling subscriptions for closed session [{}]"</span><span class="token punctuation">,</span> deviceId<span class="token punctuation">,</span> sessionId<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        sessions<span class="token punctuation">.</span><span class="token function">remove</span><span class="token punctuation">(</span>sessionId<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        attributeSubscriptions<span class="token punctuation">.</span><span class="token function">remove</span><span class="token punctuation">(</span>sessionId<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        rpcSubscriptions<span class="token punctuation">.</span><span class="token function">remove</span><span class="token punctuation">(</span>sessionId<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token keyword">if</span> <span class="token punctuation">(</span>sessions<span class="token punctuation">.</span><span class="token function">isEmpty</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token function">reportSessionClose</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">        <span class="token function">dumpSessions</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>最终的凭证校验的代码在<code v-pre>DefaultTransportApiService::validateCredentials</code>由<code v-pre>DefaultTransportApiService::handle</code>调用。</p>
<div class="language-java line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre v-pre><code><span class="line"><span class="token keyword">private</span> <span class="token class-name">ListenableFuture</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">TransportApiResponseMsg</span><span class="token punctuation">></span></span> <span class="token function">validateCredentials</span><span class="token punctuation">(</span><span class="token class-name">TransportProtos<span class="token punctuation">.</span>ValidateBasicMqttCredRequestMsg</span> mqtt<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token class-name">DeviceCredentials</span> credentials<span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token class-name">StringUtils</span><span class="token punctuation">.</span><span class="token function">isEmpty</span><span class="token punctuation">(</span>mqtt<span class="token punctuation">.</span><span class="token function">getUserName</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">        credentials <span class="token operator">=</span> <span class="token function">checkMqttCredentials</span><span class="token punctuation">(</span>mqtt<span class="token punctuation">,</span> <span class="token class-name">EncryptionUtil</span><span class="token punctuation">.</span><span class="token function">getSha3Hash</span><span class="token punctuation">(</span>mqtt<span class="token punctuation">.</span><span class="token function">getClientId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token keyword">if</span> <span class="token punctuation">(</span>credentials <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token keyword">return</span> <span class="token function">getDeviceInfo</span><span class="token punctuation">(</span>credentials<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token keyword">return</span> <span class="token function">getEmptyTransportApiResponseFuture</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span></span>
<span class="line">        credentials <span class="token operator">=</span> deviceCredentialsService<span class="token punctuation">.</span><span class="token function">findDeviceCredentialsByCredentialsId</span><span class="token punctuation">(</span></span>
<span class="line">                <span class="token class-name">EncryptionUtil</span><span class="token punctuation">.</span><span class="token function">getSha3Hash</span><span class="token punctuation">(</span><span class="token string">"|"</span><span class="token punctuation">,</span> mqtt<span class="token punctuation">.</span><span class="token function">getClientId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> mqtt<span class="token punctuation">.</span><span class="token function">getUserName</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token function">checkIsMqttCredentials</span><span class="token punctuation">(</span>credentials<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token keyword">var</span> validationResult <span class="token operator">=</span> <span class="token function">validateMqttCredentials</span><span class="token punctuation">(</span>mqtt<span class="token punctuation">,</span> credentials<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token constant">VALID</span><span class="token punctuation">.</span><span class="token function">equals</span><span class="token punctuation">(</span>validationResult<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                <span class="token keyword">return</span> <span class="token function">getDeviceInfo</span><span class="token punctuation">(</span>credentials<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token constant">PASSWORD_MISMATCH</span><span class="token punctuation">.</span><span class="token function">equals</span><span class="token punctuation">(</span>validationResult<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                <span class="token keyword">return</span> <span class="token function">getEmptyTransportApiResponseFuture</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span></span>
<span class="line">                <span class="token keyword">return</span> <span class="token function">validateUserNameCredentials</span><span class="token punctuation">(</span>mqtt<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token punctuation">}</span></span>
<span class="line">        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token keyword">return</span> <span class="token function">validateUserNameCredentials</span><span class="token punctuation">(</span>mqtt<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>下面校验访问令牌和MQTT认证。</p>
<div class="language-java line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre v-pre><code><span class="line"><span class="token keyword">private</span> <span class="token class-name">ListenableFuture</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token class-name">TransportApiResponseMsg</span><span class="token punctuation">></span></span> <span class="token function">validateUserNameCredentials</span><span class="token punctuation">(</span><span class="token class-name">TransportProtos<span class="token punctuation">.</span>ValidateBasicMqttCredRequestMsg</span> mqtt<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token class-name">DeviceCredentials</span> credentials <span class="token operator">=</span> deviceCredentialsService<span class="token punctuation">.</span><span class="token function">findDeviceCredentialsByCredentialsId</span><span class="token punctuation">(</span>mqtt<span class="token punctuation">.</span><span class="token function">getUserName</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">if</span> <span class="token punctuation">(</span>credentials <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token keyword">switch</span> <span class="token punctuation">(</span>credentials<span class="token punctuation">.</span><span class="token function">getCredentialsType</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token keyword">case</span> <span class="token constant">ACCESS_TOKEN</span><span class="token operator">:</span></span>
<span class="line">                <span class="token keyword">return</span> <span class="token function">getDeviceInfo</span><span class="token punctuation">(</span>credentials<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token keyword">case</span> <span class="token constant">MQTT_BASIC</span><span class="token operator">:</span></span>
<span class="line">                <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token constant">VALID</span><span class="token punctuation">.</span><span class="token function">equals</span><span class="token punctuation">(</span><span class="token function">validateMqttCredentials</span><span class="token punctuation">(</span>mqtt<span class="token punctuation">,</span> credentials<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                    <span class="token keyword">return</span> <span class="token function">getDeviceInfo</span><span class="token punctuation">(</span>credentials<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span></span>
<span class="line">                    <span class="token keyword">return</span> <span class="token function">getEmptyTransportApiResponseFuture</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                <span class="token punctuation">}</span></span>
<span class="line">        <span class="token punctuation">}</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token function">getEmptyTransportApiResponseFuture</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>绕来绕去，脑袋都要炸了，这也是我不喜欢Java的原因。再加上ThingsBoard还用了类似于Akka的Actor模型，就更加增大了复杂度。</p>
</div></template>


